--liquibase formatted sql
--changeset skkil:00007-notifications
--
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    actor_id BIGINT,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'UNREAD',
    entity_type VARCHAR(50),
    entity_id BIGINT,
    payload JSONB NOT NULL DEFAULT '{}',
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(actor_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_notifications_user_created_id ON notifications(user_id, created_at DESC, id DESC);

CREATE TABLE notification_preferences (
    user_id BIGINT PRIMARY KEY,
    in_app_enabled BOOLEAN NOT NULL DEFAULT true,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
