/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  ActivePromotionResponseList,
  AdminPromotionSignupResponseList,
  CreatePromotionRequest,
  CreatePromotionSignupRequest,
  PromotionResponse,
  PromotionResponseList,
  PromotionSignupResponse,
  UpdatePromotionRequest,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getPromotionsResponse200 = {
  data: PromotionResponseList;
  status: 200;
};

export type getPromotionsResponseSuccess = getPromotionsResponse200 & {
  headers: Headers;
};
export type getPromotionsResponse = getPromotionsResponseSuccess;

export const getGetPromotionsUrl = () => {
  return `/admin/promotions`;
};

/**
 * 모든 프로모션 목록을 조회합니다. 관리자만 접근할 수 있습니다.
 * @summary Get Promotions
 */
export const getPromotions = async (
  options?: RequestInit,
): Promise<getPromotionsResponse> => {
  return api<getPromotionsResponse>(getGetPromotionsUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getGetPromotionsQueryKey = () => {
  return [`/admin/promotions`] as const;
};

export const getGetPromotionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPromotions>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getPromotions>>, TError, TData>
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPromotionsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPromotions>>> = ({
    signal,
  }) => getPromotions({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPromotions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPromotionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPromotions>>
>;
export type GetPromotionsQueryError = ErrorType<unknown>;

export function useGetPromotions<
  TData = Awaited<ReturnType<typeof getPromotions>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPromotions>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPromotions>>,
          TError,
          Awaited<ReturnType<typeof getPromotions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPromotions<
  TData = Awaited<ReturnType<typeof getPromotions>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPromotions>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPromotions>>,
          TError,
          Awaited<ReturnType<typeof getPromotions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPromotions<
  TData = Awaited<ReturnType<typeof getPromotions>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPromotions>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Promotions
 */

export function useGetPromotions<
  TData = Awaited<ReturnType<typeof getPromotions>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPromotions>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPromotionsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type createPromotionResponse201 = {
  data: PromotionResponse;
  status: 201;
};

export type createPromotionResponseSuccess = createPromotionResponse201 & {
  headers: Headers;
};
export type createPromotionResponse = createPromotionResponseSuccess;

export const getCreatePromotionUrl = () => {
  return `/admin/promotions`;
};

/**
 * 새 프로모션을 생성합니다. 관리자만 접근할 수 있습니다. 생성 직후에는 비활성 상태입니다.
 * @summary Create Promotion
 */
export const createPromotion = async (
  createPromotionRequest?: CreatePromotionRequest,
  options?: RequestInit,
): Promise<createPromotionResponse> => {
  return api<createPromotionResponse>(getCreatePromotionUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPromotionRequest),
  });
};

export const getCreatePromotionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPromotion>>,
    TError,
    { data?: CreatePromotionRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPromotion>>,
  TError,
  { data?: CreatePromotionRequest },
  TContext
> => {
  const mutationKey = ['createPromotion'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPromotion>>,
    { data?: CreatePromotionRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createPromotion(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePromotionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPromotion>>
>;
export type CreatePromotionMutationBody = CreatePromotionRequest | undefined;
export type CreatePromotionMutationError = ErrorType<unknown>;

/**
 * @summary Create Promotion
 */
export const useCreatePromotion = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPromotion>>,
      TError,
      { data?: CreatePromotionRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPromotion>>,
  TError,
  { data?: CreatePromotionRequest },
  TContext
> => {
  return useMutation(getCreatePromotionMutationOptions(options), queryClient);
};
export type updatePromotionResponse200 = {
  data: PromotionResponse;
  status: 200;
};

export type updatePromotionResponseSuccess = updatePromotionResponse200 & {
  headers: Headers;
};
export type updatePromotionResponse = updatePromotionResponseSuccess;

export const getUpdatePromotionUrl = (id: string) => {
  return `/admin/promotions/${id}`;
};

/**
 * 프로모션의 연결된 게시글과 신청 필드를 수정합니다. 관리자만 접근할 수 있습니다.
 * @summary Update Promotion
 */
export const updatePromotion = async (
  id: string,
  updatePromotionRequest?: UpdatePromotionRequest,
  options?: RequestInit,
): Promise<updatePromotionResponse> => {
  return api<updatePromotionResponse>(getUpdatePromotionUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePromotionRequest),
  });
};

export const getUpdatePromotionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePromotion>>,
    TError,
    { id: string; data?: UpdatePromotionRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePromotion>>,
  TError,
  { id: string; data?: UpdatePromotionRequest },
  TContext
> => {
  const mutationKey = ['updatePromotion'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePromotion>>,
    { id: string; data?: UpdatePromotionRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return updatePromotion(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdatePromotionMutationResult = NonNullable<
  Awaited<ReturnType<typeof updatePromotion>>
>;
export type UpdatePromotionMutationBody = UpdatePromotionRequest | undefined;
export type UpdatePromotionMutationError = ErrorType<unknown>;

/**
 * @summary Update Promotion
 */
export const useUpdatePromotion = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePromotion>>,
      TError,
      { id: string; data?: UpdatePromotionRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updatePromotion>>,
  TError,
  { id: string; data?: UpdatePromotionRequest },
  TContext
> => {
  return useMutation(getUpdatePromotionMutationOptions(options), queryClient);
};
export type activatePromotionResponse200 = {
  data: PromotionResponse;
  status: 200;
};

export type activatePromotionResponseSuccess = activatePromotionResponse200 & {
  headers: Headers;
};
export type activatePromotionResponse = activatePromotionResponseSuccess;

export const getActivatePromotionUrl = (id: string) => {
  return `/admin/promotions/${id}/activate`;
};

/**
 * 프로모션을 활성화합니다. 관리자만 접근할 수 있습니다.
 * @summary Activate Promotion
 */
export const activatePromotion = async (
  id: string,
  options?: RequestInit,
): Promise<activatePromotionResponse> => {
  return api<activatePromotionResponse>(getActivatePromotionUrl(id), {
    ...options,
    method: 'PATCH',
  });
};

export const getActivatePromotionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof activatePromotion>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof activatePromotion>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['activatePromotion'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof activatePromotion>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return activatePromotion(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ActivatePromotionMutationResult = NonNullable<
  Awaited<ReturnType<typeof activatePromotion>>
>;

export type ActivatePromotionMutationError = ErrorType<unknown>;

/**
 * @summary Activate Promotion
 */
export const useActivatePromotion = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof activatePromotion>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof activatePromotion>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getActivatePromotionMutationOptions(options), queryClient);
};
export type deactivatePromotionResponse200 = {
  data: PromotionResponse;
  status: 200;
};

export type deactivatePromotionResponseSuccess =
  deactivatePromotionResponse200 & {
    headers: Headers;
  };
export type deactivatePromotionResponse = deactivatePromotionResponseSuccess;

export const getDeactivatePromotionUrl = (id: string) => {
  return `/admin/promotions/${id}/deactivate`;
};

/**
 * 프로모션을 비활성화합니다. 관리자만 접근할 수 있습니다.
 * @summary Deactivate Promotion
 */
export const deactivatePromotion = async (
  id: string,
  options?: RequestInit,
): Promise<deactivatePromotionResponse> => {
  return api<deactivatePromotionResponse>(getDeactivatePromotionUrl(id), {
    ...options,
    method: 'PATCH',
  });
};

export const getDeactivatePromotionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deactivatePromotion>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deactivatePromotion>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deactivatePromotion'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deactivatePromotion>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deactivatePromotion(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeactivatePromotionMutationResult = NonNullable<
  Awaited<ReturnType<typeof deactivatePromotion>>
>;

export type DeactivatePromotionMutationError = ErrorType<unknown>;

/**
 * @summary Deactivate Promotion
 */
export const useDeactivatePromotion = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deactivatePromotion>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deactivatePromotion>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getDeactivatePromotionMutationOptions(options),
    queryClient,
  );
};
export type getPromotionSignupsResponse200 = {
  data: AdminPromotionSignupResponseList;
  status: 200;
};

export type getPromotionSignupsResponseSuccess =
  getPromotionSignupsResponse200 & {
    headers: Headers;
  };
export type getPromotionSignupsResponse = getPromotionSignupsResponseSuccess;

export const getGetPromotionSignupsUrl = (id: string) => {
  return `/admin/promotions/${id}/signups`;
};

/**
 * 프로모션에 신청한 유저 목록을 조회합니다. 관리자만 접근할 수 있습니다.
 * @summary Get Promotion Signups
 */
export const getPromotionSignups = async (
  id: string,
  options?: RequestInit,
): Promise<getPromotionSignupsResponse> => {
  return api<getPromotionSignupsResponse>(getGetPromotionSignupsUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getGetPromotionSignupsQueryKey = (id: string) => {
  return [`/admin/promotions/${id}/signups`] as const;
};

export const getGetPromotionSignupsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPromotionSignups>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPromotionSignups>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPromotionSignupsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPromotionSignups>>
  > = ({ signal }) => getPromotionSignups(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getPromotionSignups>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPromotionSignupsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPromotionSignups>>
>;
export type GetPromotionSignupsQueryError = ErrorType<unknown>;

export function useGetPromotionSignups<
  TData = Awaited<ReturnType<typeof getPromotionSignups>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPromotionSignups>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPromotionSignups>>,
          TError,
          Awaited<ReturnType<typeof getPromotionSignups>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPromotionSignups<
  TData = Awaited<ReturnType<typeof getPromotionSignups>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPromotionSignups>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPromotionSignups>>,
          TError,
          Awaited<ReturnType<typeof getPromotionSignups>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPromotionSignups<
  TData = Awaited<ReturnType<typeof getPromotionSignups>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPromotionSignups>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Promotion Signups
 */

export function useGetPromotionSignups<
  TData = Awaited<ReturnType<typeof getPromotionSignups>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPromotionSignups>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPromotionSignupsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getActivePromotionsResponse200 = {
  data: ActivePromotionResponseList;
  status: 200;
};

export type getActivePromotionsResponseSuccess =
  getActivePromotionsResponse200 & {
    headers: Headers;
  };
export type getActivePromotionsResponse = getActivePromotionsResponseSuccess;

export const getGetActivePromotionsUrl = () => {
  return `/promotions/active`;
};

/**
 * 현재 진행 중인 모든 프로모션과 내 신청 상태를 조회합니다.
 * @summary Get Active Promotions
 */
export const getActivePromotions = async (
  options?: RequestInit,
): Promise<getActivePromotionsResponse> => {
  return api<getActivePromotionsResponse>(getGetActivePromotionsUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getGetActivePromotionsQueryKey = () => {
  return [`/promotions/active`] as const;
};

export const getGetActivePromotionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getActivePromotions>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getActivePromotions>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetActivePromotionsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getActivePromotions>>
  > = ({ signal }) => getActivePromotions({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getActivePromotions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetActivePromotionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getActivePromotions>>
>;
export type GetActivePromotionsQueryError = ErrorType<unknown>;

export function useGetActivePromotions<
  TData = Awaited<ReturnType<typeof getActivePromotions>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getActivePromotions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActivePromotions>>,
          TError,
          Awaited<ReturnType<typeof getActivePromotions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetActivePromotions<
  TData = Awaited<ReturnType<typeof getActivePromotions>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getActivePromotions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getActivePromotions>>,
          TError,
          Awaited<ReturnType<typeof getActivePromotions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetActivePromotions<
  TData = Awaited<ReturnType<typeof getActivePromotions>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getActivePromotions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Active Promotions
 */

export function useGetActivePromotions<
  TData = Awaited<ReturnType<typeof getActivePromotions>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getActivePromotions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetActivePromotionsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type submitPromotionSignupResponse200 = {
  data: PromotionSignupResponse;
  status: 200;
};

export type submitPromotionSignupResponseSuccess =
  submitPromotionSignupResponse200 & {
    headers: Headers;
  };
export type submitPromotionSignupResponse =
  submitPromotionSignupResponseSuccess;

export const getSubmitPromotionSignupUrl = (promotionId: string) => {
  return `/promotions/${promotionId}/signups`;
};

/**
 * 활성 프로모션에 신청합니다. 이미 신청한 경우 제출한 데이터를 갱신합니다.
 * @summary Submit Promotion Signup
 */
export const submitPromotionSignup = async (
  promotionId: string,
  createPromotionSignupRequest?: CreatePromotionSignupRequest,
  options?: RequestInit,
): Promise<submitPromotionSignupResponse> => {
  return api<submitPromotionSignupResponse>(
    getSubmitPromotionSignupUrl(promotionId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createPromotionSignupRequest),
    },
  );
};

export const getSubmitPromotionSignupMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitPromotionSignup>>,
    TError,
    { promotionId: string; data?: CreatePromotionSignupRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitPromotionSignup>>,
  TError,
  { promotionId: string; data?: CreatePromotionSignupRequest },
  TContext
> => {
  const mutationKey = ['submitPromotionSignup'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitPromotionSignup>>,
    { promotionId: string; data?: CreatePromotionSignupRequest }
  > = (props) => {
    const { promotionId, data } = props ?? {};

    return submitPromotionSignup(promotionId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitPromotionSignupMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitPromotionSignup>>
>;
export type SubmitPromotionSignupMutationBody =
  | CreatePromotionSignupRequest
  | undefined;
export type SubmitPromotionSignupMutationError = ErrorType<unknown>;

/**
 * @summary Submit Promotion Signup
 */
export const useSubmitPromotionSignup = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof submitPromotionSignup>>,
      TError,
      { promotionId: string; data?: CreatePromotionSignupRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof submitPromotionSignup>>,
  TError,
  { promotionId: string; data?: CreatePromotionSignupRequest },
  TContext
> => {
  return useMutation(
    getSubmitPromotionSignupMutationOptions(options),
    queryClient,
  );
};
