/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type { GetChannelTalkIdentityResponse } from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getChannelTalkIdentityResponse200 = {
  data: GetChannelTalkIdentityResponse;
  status: 200;
};

export type getChannelTalkIdentityResponseSuccess =
  getChannelTalkIdentityResponse200 & {
    headers: Headers;
  };
export type getChannelTalkIdentityResponse =
  getChannelTalkIdentityResponseSuccess;

export const getGetChannelTalkIdentityUrl = () => {
  return `/channel-talk/identity`;
};

/**
 * Get Channel Talk Identity
 * @summary Get Channel Talk Identity
 */
export const getChannelTalkIdentity = async (
  options?: RequestInit,
): Promise<getChannelTalkIdentityResponse> => {
  return api<getChannelTalkIdentityResponse>(getGetChannelTalkIdentityUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getGetChannelTalkIdentityQueryKey = () => {
  return [`/channel-talk/identity`] as const;
};

export const getGetChannelTalkIdentityQueryOptions = <
  TData = Awaited<ReturnType<typeof getChannelTalkIdentity>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getChannelTalkIdentity>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetChannelTalkIdentityQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getChannelTalkIdentity>>
  > = ({ signal }) => getChannelTalkIdentity({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getChannelTalkIdentity>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChannelTalkIdentityQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChannelTalkIdentity>>
>;
export type GetChannelTalkIdentityQueryError = ErrorType<unknown>;

export function useGetChannelTalkIdentity<
  TData = Awaited<ReturnType<typeof getChannelTalkIdentity>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelTalkIdentity>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChannelTalkIdentity>>,
          TError,
          Awaited<ReturnType<typeof getChannelTalkIdentity>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChannelTalkIdentity<
  TData = Awaited<ReturnType<typeof getChannelTalkIdentity>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelTalkIdentity>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChannelTalkIdentity>>,
          TError,
          Awaited<ReturnType<typeof getChannelTalkIdentity>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChannelTalkIdentity<
  TData = Awaited<ReturnType<typeof getChannelTalkIdentity>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelTalkIdentity>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Channel Talk Identity
 */

export function useGetChannelTalkIdentity<
  TData = Awaited<ReturnType<typeof getChannelTalkIdentity>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChannelTalkIdentity>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetChannelTalkIdentityQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
