/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  AddPostToCollectionRequest,
  CollectionSummary,
  CreateCollectionRequest,
  CreateCollectionResponse,
  GetCollectionPostsParams,
  GetCollectionPostsResponse,
  GetCollectionsResponse,
  GetProjectCollectionsParams,
  GetUserCollectionsParams,
  UpdateCollectionRequest,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type createCollectionResponse201 = {
  data: CreateCollectionResponse;
  status: 201;
};

export type createCollectionResponseSuccess = createCollectionResponse201 & {
  headers: Headers;
};
export type createCollectionResponse = createCollectionResponseSuccess;

export const getCreateCollectionUrl = () => {
  return `/collections`;
};

/**
 * 개인 컬렉션을 생성한다.
 * @summary Create Collection
 */
export const createCollection = async (
  createCollectionRequest?: CreateCollectionRequest,
  options?: RequestInit,
): Promise<createCollectionResponse> => {
  return api<createCollectionResponse>(getCreateCollectionUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCollectionRequest),
  });
};

export const getCreateCollectionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCollection>>,
    TError,
    { data?: CreateCollectionRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCollection>>,
  TError,
  { data?: CreateCollectionRequest },
  TContext
> => {
  const mutationKey = ['createCollection'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCollection>>,
    { data?: CreateCollectionRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createCollection(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCollection>>
>;
export type CreateCollectionMutationBody = CreateCollectionRequest | undefined;
export type CreateCollectionMutationError = ErrorType<unknown>;

/**
 * @summary Create Collection
 */
export const useCreateCollection = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCollection>>,
      TError,
      { data?: CreateCollectionRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createCollection>>,
  TError,
  { data?: CreateCollectionRequest },
  TContext
> => {
  return useMutation(getCreateCollectionMutationOptions(options), queryClient);
};
export type getCollectionResponse200 = {
  data: CollectionSummary;
  status: 200;
};

export type getCollectionResponseSuccess = getCollectionResponse200 & {
  headers: Headers;
};
export type getCollectionResponse = getCollectionResponseSuccess;

export const getGetCollectionUrl = (externalId: string) => {
  return `/collections/${externalId}`;
};

/**
 * 컬렉션 메타데이터를 조회한다. (게시글 항목은 별도 API 로 페이지네이션한다)
 * @summary Get Collection
 */
export const getCollection = async (
  externalId: string,
  options?: RequestInit,
): Promise<getCollectionResponse> => {
  return api<getCollectionResponse>(getGetCollectionUrl(externalId), {
    ...options,
    method: 'GET',
  });
};

export const getGetCollectionQueryKey = (externalId: string) => {
  return [`/collections/${externalId}`] as const;
};

export const getGetCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof getCollection>>,
  TError = ErrorType<unknown>,
>(
  externalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCollection>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCollectionQueryKey(externalId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCollection>>> = ({
    signal,
  }) => getCollection(externalId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: externalId !== null && externalId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCollection>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCollectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCollection>>
>;
export type GetCollectionQueryError = ErrorType<unknown>;

export function useGetCollection<
  TData = Awaited<ReturnType<typeof getCollection>>,
  TError = ErrorType<unknown>,
>(
  externalId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCollection>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollection>>,
          TError,
          Awaited<ReturnType<typeof getCollection>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCollection<
  TData = Awaited<ReturnType<typeof getCollection>>,
  TError = ErrorType<unknown>,
>(
  externalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCollection>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollection>>,
          TError,
          Awaited<ReturnType<typeof getCollection>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCollection<
  TData = Awaited<ReturnType<typeof getCollection>>,
  TError = ErrorType<unknown>,
>(
  externalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCollection>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Collection
 */

export function useGetCollection<
  TData = Awaited<ReturnType<typeof getCollection>>,
  TError = ErrorType<unknown>,
>(
  externalId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCollection>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCollectionQueryOptions(externalId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type deleteCollectionResponse204 = {
  data: void;
  status: 204;
};

export type deleteCollectionResponseSuccess = deleteCollectionResponse204 & {
  headers: Headers;
};
export type deleteCollectionResponse = deleteCollectionResponseSuccess;

export const getDeleteCollectionUrl = (externalId: string) => {
  return `/collections/${externalId}`;
};

/**
 * 컬렉션을 삭제한다. (컬렉션 삭제 권한 필요)
 * @summary Delete Collection
 */
export const deleteCollection = async (
  externalId: string,
  options?: RequestInit,
): Promise<deleteCollectionResponse> => {
  return api<deleteCollectionResponse>(getDeleteCollectionUrl(externalId), {
    ...options,
    method: 'DELETE',
  });
};

export const getDeleteCollectionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCollection>>,
    TError,
    { externalId: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCollection>>,
  TError,
  { externalId: string },
  TContext
> => {
  const mutationKey = ['deleteCollection'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCollection>>,
    { externalId: string }
  > = (props) => {
    const { externalId } = props ?? {};

    return deleteCollection(externalId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCollection>>
>;

export type DeleteCollectionMutationError = ErrorType<unknown>;

/**
 * @summary Delete Collection
 */
export const useDeleteCollection = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCollection>>,
      TError,
      { externalId: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCollection>>,
  TError,
  { externalId: string },
  TContext
> => {
  return useMutation(getDeleteCollectionMutationOptions(options), queryClient);
};
export type updateCollectionResponse204 = {
  data: void;
  status: 204;
};

export type updateCollectionResponseSuccess = updateCollectionResponse204 & {
  headers: Headers;
};
export type updateCollectionResponse = updateCollectionResponseSuccess;

export const getUpdateCollectionUrl = (externalId: string) => {
  return `/collections/${externalId}`;
};

/**
 * 컬렉션 메타데이터를 수정한다. 생략된 필드는 기존 값을 유지한다. (컬렉션 편집 권한 필요)
 * @summary Update Collection
 */
export const updateCollection = async (
  externalId: string,
  updateCollectionRequest?: UpdateCollectionRequest,
  options?: RequestInit,
): Promise<updateCollectionResponse> => {
  return api<updateCollectionResponse>(getUpdateCollectionUrl(externalId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateCollectionRequest),
  });
};

export const getUpdateCollectionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCollection>>,
    TError,
    { externalId: string; data?: UpdateCollectionRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCollection>>,
  TError,
  { externalId: string; data?: UpdateCollectionRequest },
  TContext
> => {
  const mutationKey = ['updateCollection'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCollection>>,
    { externalId: string; data?: UpdateCollectionRequest }
  > = (props) => {
    const { externalId, data } = props ?? {};

    return updateCollection(externalId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCollection>>
>;
export type UpdateCollectionMutationBody = UpdateCollectionRequest | undefined;
export type UpdateCollectionMutationError = ErrorType<unknown>;

/**
 * @summary Update Collection
 */
export const useUpdateCollection = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCollection>>,
      TError,
      { externalId: string; data?: UpdateCollectionRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCollection>>,
  TError,
  { externalId: string; data?: UpdateCollectionRequest },
  TContext
> => {
  return useMutation(getUpdateCollectionMutationOptions(options), queryClient);
};
export type getCollectionPostsResponse200 = {
  data: GetCollectionPostsResponse;
  status: 200;
};

export type getCollectionPostsResponseSuccess =
  getCollectionPostsResponse200 & {
    headers: Headers;
  };
export type getCollectionPostsResponse = getCollectionPostsResponseSuccess;

export const getGetCollectionPostsUrl = (
  externalId: string,
  params?: GetCollectionPostsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/collections/${externalId}/posts?${stringifiedParams}`
    : `/collections/${externalId}/posts`;
};

/**
 * 컬렉션 안의 게시글 항목을 커서로 페이지네이션한다. 열람 불가·삭제된 항목은 정보를 노출하지 않는 tombstone 으로 내려온다.
 * @summary Get Collection Posts
 */
export const getCollectionPosts = async (
  externalId: string,
  params?: GetCollectionPostsParams,
  options?: RequestInit,
): Promise<getCollectionPostsResponse> => {
  return api<getCollectionPostsResponse>(
    getGetCollectionPostsUrl(externalId, params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetCollectionPostsInfiniteQueryKey = (
  externalId: string,
  params?: GetCollectionPostsParams,
) => {
  return [
    'infinite',
    `/collections/${externalId}/posts`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetCollectionPostsQueryKey = (
  externalId: string,
  params?: GetCollectionPostsParams,
) => {
  return [
    `/collections/${externalId}/posts`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetCollectionPostsInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getCollectionPosts>>,
    GetCollectionPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  externalId: string,
  params?: GetCollectionPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getCollectionPosts>>,
        TError,
        TData,
        QueryKey,
        GetCollectionPostsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetCollectionPostsInfiniteQueryKey(externalId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCollectionPosts>>,
    QueryKey,
    GetCollectionPostsParams['after']
  > = ({ signal, pageParam }) =>
    getCollectionPosts(
      externalId,
      { ...params, after: pageParam ?? params?.['after'] },
      { signal, ...requestOptions },
    );

  return {
    queryKey,
    queryFn,
    enabled: externalId !== null && externalId !== undefined,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getCollectionPosts>>,
    TError,
    TData,
    QueryKey,
    GetCollectionPostsParams['after']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCollectionPostsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCollectionPosts>>
>;
export type GetCollectionPostsInfiniteQueryError = ErrorType<unknown>;

export function useGetCollectionPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getCollectionPosts>>,
    GetCollectionPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  externalId: string,
  params: undefined | GetCollectionPostsParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getCollectionPosts>>,
        TError,
        TData,
        QueryKey,
        GetCollectionPostsParams['after']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollectionPosts>>,
          TError,
          Awaited<ReturnType<typeof getCollectionPosts>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCollectionPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getCollectionPosts>>,
    GetCollectionPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  externalId: string,
  params?: GetCollectionPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getCollectionPosts>>,
        TError,
        TData,
        QueryKey,
        GetCollectionPostsParams['after']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollectionPosts>>,
          TError,
          Awaited<ReturnType<typeof getCollectionPosts>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCollectionPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getCollectionPosts>>,
    GetCollectionPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  externalId: string,
  params?: GetCollectionPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getCollectionPosts>>,
        TError,
        TData,
        QueryKey,
        GetCollectionPostsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Collection Posts
 */

export function useGetCollectionPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getCollectionPosts>>,
    GetCollectionPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  externalId: string,
  params?: GetCollectionPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getCollectionPosts>>,
        TError,
        TData,
        QueryKey,
        GetCollectionPostsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCollectionPostsInfiniteQueryOptions(
    externalId,
    params,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetCollectionPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getCollectionPosts>>,
  TError = ErrorType<unknown>,
>(
  externalId: string,
  params?: GetCollectionPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCollectionPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCollectionPostsQueryKey(externalId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCollectionPosts>>
  > = ({ signal }) =>
    getCollectionPosts(externalId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: externalId !== null && externalId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCollectionPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCollectionPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCollectionPosts>>
>;
export type GetCollectionPostsQueryError = ErrorType<unknown>;

export function useGetCollectionPosts<
  TData = Awaited<ReturnType<typeof getCollectionPosts>>,
  TError = ErrorType<unknown>,
>(
  externalId: string,
  params: undefined | GetCollectionPostsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCollectionPosts>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollectionPosts>>,
          TError,
          Awaited<ReturnType<typeof getCollectionPosts>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCollectionPosts<
  TData = Awaited<ReturnType<typeof getCollectionPosts>>,
  TError = ErrorType<unknown>,
>(
  externalId: string,
  params?: GetCollectionPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCollectionPosts>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCollectionPosts>>,
          TError,
          Awaited<ReturnType<typeof getCollectionPosts>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCollectionPosts<
  TData = Awaited<ReturnType<typeof getCollectionPosts>>,
  TError = ErrorType<unknown>,
>(
  externalId: string,
  params?: GetCollectionPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCollectionPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Collection Posts
 */

export function useGetCollectionPosts<
  TData = Awaited<ReturnType<typeof getCollectionPosts>>,
  TError = ErrorType<unknown>,
>(
  externalId: string,
  params?: GetCollectionPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCollectionPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCollectionPostsQueryOptions(
    externalId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type addPostToCollectionResponse204 = {
  data: void;
  status: 204;
};

export type addPostToCollectionResponseSuccess =
  addPostToCollectionResponse204 & {
    headers: Headers;
  };
export type addPostToCollectionResponse = addPostToCollectionResponseSuccess;

export const getAddPostToCollectionUrl = (externalId: string) => {
  return `/collections/${externalId}/posts`;
};

/**
 * 컬렉션에 게시글을 추가한다. 게시글은 (projectHandle, postHandle) 튜플로 참조하며, 요청자가 현재 열람 가능한 게시글만 추가할 수 있다. (컬렉션 편집 권한 필요)
 * @summary Add Post To Collection
 */
export const addPostToCollection = async (
  externalId: string,
  addPostToCollectionRequest?: AddPostToCollectionRequest,
  options?: RequestInit,
): Promise<addPostToCollectionResponse> => {
  return api<addPostToCollectionResponse>(
    getAddPostToCollectionUrl(externalId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(addPostToCollectionRequest),
    },
  );
};

export const getAddPostToCollectionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addPostToCollection>>,
    TError,
    { externalId: string; data?: AddPostToCollectionRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addPostToCollection>>,
  TError,
  { externalId: string; data?: AddPostToCollectionRequest },
  TContext
> => {
  const mutationKey = ['addPostToCollection'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addPostToCollection>>,
    { externalId: string; data?: AddPostToCollectionRequest }
  > = (props) => {
    const { externalId, data } = props ?? {};

    return addPostToCollection(externalId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddPostToCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof addPostToCollection>>
>;
export type AddPostToCollectionMutationBody =
  | AddPostToCollectionRequest
  | undefined;
export type AddPostToCollectionMutationError = ErrorType<unknown>;

/**
 * @summary Add Post To Collection
 */
export const useAddPostToCollection = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addPostToCollection>>,
      TError,
      { externalId: string; data?: AddPostToCollectionRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addPostToCollection>>,
  TError,
  { externalId: string; data?: AddPostToCollectionRequest },
  TContext
> => {
  return useMutation(
    getAddPostToCollectionMutationOptions(options),
    queryClient,
  );
};
export type removeCollectionItemResponse204 = {
  data: void;
  status: 204;
};

export type removeCollectionItemResponseSuccess =
  removeCollectionItemResponse204 & {
    headers: Headers;
  };
export type removeCollectionItemResponse = removeCollectionItemResponseSuccess;

export const getRemoveCollectionItemUrl = (
  externalId: string,
  collectionPostId: string,
) => {
  return `/collections/${externalId}/items/${collectionPostId}`;
};

/**
 * 컬렉션 항목을 항목 ID(collectionPostId) 로 제거한다. 원본이 삭제·숨김된 tombstone 항목도 제거할 수 있다. (컬렉션 편집 권한 필요)
 * @summary Remove Collection Item
 */
export const removeCollectionItem = async (
  externalId: string,
  collectionPostId: string,
  options?: RequestInit,
): Promise<removeCollectionItemResponse> => {
  return api<removeCollectionItemResponse>(
    getRemoveCollectionItemUrl(externalId, collectionPostId),
    {
      ...options,
      method: 'DELETE',
    },
  );
};

export const getRemoveCollectionItemMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeCollectionItem>>,
    TError,
    { externalId: string; collectionPostId: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeCollectionItem>>,
  TError,
  { externalId: string; collectionPostId: string },
  TContext
> => {
  const mutationKey = ['removeCollectionItem'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeCollectionItem>>,
    { externalId: string; collectionPostId: string }
  > = (props) => {
    const { externalId, collectionPostId } = props ?? {};

    return removeCollectionItem(externalId, collectionPostId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveCollectionItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeCollectionItem>>
>;

export type RemoveCollectionItemMutationError = ErrorType<unknown>;

/**
 * @summary Remove Collection Item
 */
export const useRemoveCollectionItem = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeCollectionItem>>,
      TError,
      { externalId: string; collectionPostId: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof removeCollectionItem>>,
  TError,
  { externalId: string; collectionPostId: string },
  TContext
> => {
  return useMutation(
    getRemoveCollectionItemMutationOptions(options),
    queryClient,
  );
};
export type getProjectCollectionsResponse200 = {
  data: GetCollectionsResponse;
  status: 200;
};

export type getProjectCollectionsResponseSuccess =
  getProjectCollectionsResponse200 & {
    headers: Headers;
  };
export type getProjectCollectionsResponse =
  getProjectCollectionsResponseSuccess;

export const getGetProjectCollectionsUrl = (
  handle: string,
  params?: GetProjectCollectionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/projects/${handle}/collections?${stringifiedParams}`
    : `/projects/${handle}/collections`;
};

/**
 * 한 프로젝트의 컬렉션 목록을 조회한다. 팀원은 모든 컬렉션을, 그 외에는 공개 프로젝트의 공개 컬렉션만 볼 수 있다.
 * @summary Get Project Collections
 */
export const getProjectCollections = async (
  handle: string,
  params?: GetProjectCollectionsParams,
  options?: RequestInit,
): Promise<getProjectCollectionsResponse> => {
  return api<getProjectCollectionsResponse>(
    getGetProjectCollectionsUrl(handle, params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetProjectCollectionsQueryKey = (
  handle: string,
  params?: GetProjectCollectionsParams,
) => {
  return [
    `/projects/${handle}/collections`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetProjectCollectionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjectCollections>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetProjectCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProjectCollectionsQueryKey(handle, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProjectCollections>>
  > = ({ signal }) =>
    getProjectCollections(handle, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: handle !== null && handle !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjectCollections>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectCollectionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjectCollections>>
>;
export type GetProjectCollectionsQueryError = ErrorType<unknown>;

export function useGetProjectCollections<
  TData = Awaited<ReturnType<typeof getProjectCollections>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params: undefined | GetProjectCollectionsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectCollections>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectCollections>>,
          TError,
          Awaited<ReturnType<typeof getProjectCollections>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectCollections<
  TData = Awaited<ReturnType<typeof getProjectCollections>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetProjectCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectCollections>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectCollections>>,
          TError,
          Awaited<ReturnType<typeof getProjectCollections>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectCollections<
  TData = Awaited<ReturnType<typeof getProjectCollections>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetProjectCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Project Collections
 */

export function useGetProjectCollections<
  TData = Awaited<ReturnType<typeof getProjectCollections>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  params?: GetProjectCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProjectCollectionsQueryOptions(
    handle,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type createProjectCollectionResponse201 = {
  data: CreateCollectionResponse;
  status: 201;
};

export type createProjectCollectionResponseSuccess =
  createProjectCollectionResponse201 & {
    headers: Headers;
  };
export type createProjectCollectionResponse =
  createProjectCollectionResponseSuccess;

export const getCreateProjectCollectionUrl = (handle: string) => {
  return `/projects/${handle}/collections`;
};

/**
 * 프로젝트 소속 컬렉션을 생성한다. (프로젝트 팀원 권한 필요)
 * @summary Create Project Collection
 */
export const createProjectCollection = async (
  handle: string,
  createCollectionRequest?: CreateCollectionRequest,
  options?: RequestInit,
): Promise<createProjectCollectionResponse> => {
  return api<createProjectCollectionResponse>(
    getCreateProjectCollectionUrl(handle),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createCollectionRequest),
    },
  );
};

export const getCreateProjectCollectionMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createProjectCollection>>,
    TError,
    { handle: string; data?: CreateCollectionRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createProjectCollection>>,
  TError,
  { handle: string; data?: CreateCollectionRequest },
  TContext
> => {
  const mutationKey = ['createProjectCollection'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createProjectCollection>>,
    { handle: string; data?: CreateCollectionRequest }
  > = (props) => {
    const { handle, data } = props ?? {};

    return createProjectCollection(handle, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateProjectCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof createProjectCollection>>
>;
export type CreateProjectCollectionMutationBody =
  | CreateCollectionRequest
  | undefined;
export type CreateProjectCollectionMutationError = ErrorType<unknown>;

/**
 * @summary Create Project Collection
 */
export const useCreateProjectCollection = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createProjectCollection>>,
      TError,
      { handle: string; data?: CreateCollectionRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createProjectCollection>>,
  TError,
  { handle: string; data?: CreateCollectionRequest },
  TContext
> => {
  return useMutation(
    getCreateProjectCollectionMutationOptions(options),
    queryClient,
  );
};
export type getUserCollectionsResponse200 = {
  data: GetCollectionsResponse;
  status: 200;
};

export type getUserCollectionsResponseSuccess =
  getUserCollectionsResponse200 & {
    headers: Headers;
  };
export type getUserCollectionsResponse = getUserCollectionsResponseSuccess;

export const getGetUserCollectionsUrl = (
  userId: string,
  params?: GetUserCollectionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/users/${userId}/collections?${stringifiedParams}`
    : `/users/${userId}/collections`;
};

/**
 * 한 사용자의 개인 컬렉션 목록을 조회한다. 비공개 컬렉션은 본인에게만 보인다.
 * @summary Get User Collections
 */
export const getUserCollections = async (
  userId: string,
  params?: GetUserCollectionsParams,
  options?: RequestInit,
): Promise<getUserCollectionsResponse> => {
  return api<getUserCollectionsResponse>(
    getGetUserCollectionsUrl(userId, params),
    {
      ...options,
      method: 'GET',
    },
  );
};

export const getGetUserCollectionsQueryKey = (
  userId: string,
  params?: GetUserCollectionsParams,
) => {
  return [`/users/${userId}/collections`, ...(params ? [params] : [])] as const;
};

export const getGetUserCollectionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserCollections>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetUserCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserCollectionsQueryKey(userId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserCollections>>
  > = ({ signal }) =>
    getUserCollections(userId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserCollections>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserCollectionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserCollections>>
>;
export type GetUserCollectionsQueryError = ErrorType<unknown>;

export function useGetUserCollections<
  TData = Awaited<ReturnType<typeof getUserCollections>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params: undefined | GetUserCollectionsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserCollections>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserCollections>>,
          TError,
          Awaited<ReturnType<typeof getUserCollections>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserCollections<
  TData = Awaited<ReturnType<typeof getUserCollections>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetUserCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserCollections>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserCollections>>,
          TError,
          Awaited<ReturnType<typeof getUserCollections>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserCollections<
  TData = Awaited<ReturnType<typeof getUserCollections>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetUserCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get User Collections
 */

export function useGetUserCollections<
  TData = Awaited<ReturnType<typeof getUserCollections>>,
  TError = ErrorType<unknown>,
>(
  userId: string,
  params?: GetUserCollectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserCollections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserCollectionsQueryOptions(
    userId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
