/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { ActivePromotionResponseListItemSignupAttachment } from './ActivePromotionResponseListItemSignupAttachment';

/**
 * 내 신청 정보
 */
export type ActivePromotionResponseListItemSignup = {
  /**
   * 신청 시각
   * @nullable
   */
  createdAt?: string | null;
  /** 제출한 데이터 */
  attachment?: ActivePromotionResponseListItemSignupAttachment;
};
