/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface AddPostToPostSeriesRequest {
  /** 시리즈에 추가할 게시글의 핸들(slug) */
  postHandle: string;
  /**
   * 추가할 위치 (지정하지 않으면 맨 뒤에 추가)
   * @nullable
   */
  position?: number | null;
  /**
   * 게시글이 속한 프로젝트 핸들 (개인 게시글인 경우 없음)
   * @nullable
   */
  projectHandle?: string | null;
}
