/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface AddPostToCollectionRequest {
  /** 게시글의 전역 유니크 식별자 (slug) */
  postHandle: string;
  /**
   * 게시글이 속한 프로젝트의 핸들 (개인 게시글이면 생략)
   * @nullable
   */
  projectHandle?: string | null;
}
