/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { AdminProjectSummaryJoinPolicy } from './AdminProjectSummaryJoinPolicy';
import type { AdminProjectSummaryOwner } from './AdminProjectSummaryOwner';

export interface AdminProjectSummary {
  /** 프로젝트 소유자 */
  owner?: AdminProjectSummaryOwner;
  /** 생성 시각 */
  createdAt: string;
  /**
   * 프로젝트 웹사이트
   * @nullable
   */
  website?: string | null;
  /** 팀원 수 */
  teammateCount: number;
  /** 프로젝트 이름 */
  name: string;
  /** 공개 여부 */
  isPublic: boolean;
  /**
   * 프로젝트 설명
   * @nullable
   */
  description?: string | null;
  /** 프로젝트 핸들 */
  handle: string;
  /**
   * 프로젝트 아이콘 URL
   * @nullable
   */
  iconUrl?: string | null;
  /** 프로젝트 ID */
  id: number;
  /** 프로젝트 참여 정책 */
  joinPolicy: AdminProjectSummaryJoinPolicy;
  /** 팔로워 수 */
  followerCount: number;
}
