/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 프로젝트 소유자
 */
export type AdminProjectSummaryOwner = {
  /** 탈퇴한 사용자인지 여부 */
  isDeleted: boolean;
  /** 유저 이름 */
  name: string;
  /** 유저 핸들 */
  handle: string;
  /**
   * 유저 프로필 이미지 URL
   * @nullable
   */
  profileImageUrl?: string | null;
};
