/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 플랫폼 역할
 */
export type AdminUserSummaryRole =
  (typeof AdminUserSummaryRole)[keyof typeof AdminUserSummaryRole];

export const AdminUserSummaryRole = {
  Admin: 'ADMIN',
  User: 'USER',
} as const;
