/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { AdminPromotionSignupResponseListItemAttachment } from './AdminPromotionSignupResponseListItemAttachment';
import type { AdminPromotionSignupResponseListItemUser } from './AdminPromotionSignupResponseListItemUser';

export type AdminPromotionSignupResponseListItem = {
  /** 신청 시각 */
  createdAt: string;
  /** 제출한 데이터 */
  attachment: AdminPromotionSignupResponseListItemAttachment;
  /** 신청 ID */
  id: number;
  /** 신청자 정보 */
  user: AdminPromotionSignupResponseListItemUser;
};
