/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { AdminUserSummaryRole } from './AdminUserSummaryRole';

export interface AdminUserSummary {
  /** 가입 시각 */
  createdAt: string;
  /**
   * 탈퇴 시각 (탈퇴하지 않았다면 null)
   * @nullable
   */
  deletedAt?: string | null;
  /** 플랫폼 역할 */
  role: AdminUserSummaryRole;
  /** 유저 이름 */
  name: string;
  /**
   * 유저 핸들
   * @nullable
   */
  handle?: string | null;
  /** 유저 ID */
  id: number;
  /** 팔로잉 수 */
  followingCount: number;
  /** 팔로워 수 */
  followerCount: number;
  /**
   * 유저 프로필 이미지 URL
   * @nullable
   */
  profileImageUrl?: string | null;
  /** 이메일 인증 여부 */
  isEmailVerified: boolean;
  /** 유저 이메일 */
  email: string;
  /** 온보딩 완료 여부 */
  isOnboarded: boolean;
}
