/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface ChangePasswordRequest {
  /** 새 비밀번호 (8-128자) */
  newPassword: string;
  /**
   * 현재 비밀번호. OAuth2 로만 가입해 비밀번호가 없는 사용자는 생략할 수 있습니다.
   * @nullable
   */
  currentPassword?: string | null;
}
