/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 컬렉션 범위 (PERSONAL: 개인, WORKSPACE: 프로젝트 소속)
 */
export type CollectionSummaryScope =
  (typeof CollectionSummaryScope)[keyof typeof CollectionSummaryScope];

export const CollectionSummaryScope = {
  Personal: 'PERSONAL',
  Workspace: 'WORKSPACE',
} as const;
