/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface ConfirmPasswordResetRequest {
  /** 새 비밀번호 (8-128자) */
  newPassword: string;
  /** 재설정 링크에 담긴 토큰 */
  token: string;
}
