/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface CreateCollectionRequest {
  /** 컬렉션 이름 (최대 255자) */
  name: string;
  /**
   * 공개 여부 (생략 시 공개)
   * @nullable
   */
  isPublic?: boolean | null;
  /**
   * 컬렉션 설명
   * @nullable
   */
  description?: string | null;
}
