/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 제출할 데이터. 키는 해당 프로모션에 등록된 필드의 key와 일치해야 합니다.
 */
export type CreatePromotionSignupRequestAttachment = {
  /**
   * 전화번호 (숫자만)
   * @nullable
   */
  phoneNumber?: string | null;
};
