/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 프로젝트 참여 정책 (미지정 시 INVITE)
 * @nullable
 */
export type CreateProjectRequestJoinPolicy =
  | (typeof CreateProjectRequestJoinPolicy)[keyof typeof CreateProjectRequestJoinPolicy]
  | null;

export const CreateProjectRequestJoinPolicy = {
  Open: 'OPEN',
  Request: 'REQUEST',
  Invite: 'INVITE',
} as const;
