/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type CreatePostRequestContentMediaIdsItem =
  | { [key: string]: unknown }
  | boolean
  | string
  | number;
