/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { CreatePromotionRequestFieldsItem } from './CreatePromotionRequestFieldsItem';

export interface CreatePromotionRequest {
  /** 연결된 게시글의 슬러그. 이미 생성된 게시글이어야 합니다. */
  postSlug: string;
  /** 신청 시 수집할 필드 목록. 빈 배열이면 신청 없이 안내만 하는 프로모션입니다. */
  fields: CreatePromotionRequestFieldsItem[];
  /** 연결된 게시글이 속한 프로젝트 핸들 */
  projectHandle: string;
}
