/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface CreateCollectionResponse {
  /** 생성된 컬렉션의 외부 식별자 (이후 모든 API 가 이 값으로 컬렉션을 참조한다) */
  externalId: string;
}
