/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { CreateProjectRequestJoinPolicy } from './CreateProjectRequestJoinPolicy';

export interface CreateProjectRequest {
  /** 프로젝트 이름 */
  name: string;
  /** 공개 여부 */
  isPublic: boolean;
  /**
   * 프로젝트 설명
   * @nullable
   */
  description?: string | null;
  /** 프로젝트 핸들 */
  handle: string;
  /**
   * 프로젝트 참여 정책 (미지정 시 INVITE)
   * @nullable
   */
  joinPolicy?: CreateProjectRequestJoinPolicy;
}
