/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetBookmarkedPostsResponsePostsNodesItemContentSummary } from './GetBookmarkedPostsResponsePostsNodesItemContentSummary';

/**
 * Node Content
 */
export type GetBookmarkedPostsResponsePostsNodesItemContent = {
  /** Post Summary */
  summary: GetBookmarkedPostsResponsePostsNodesItemContentSummary;
  /** Whether the current user bookmarked this post */
  bookmarked: boolean;
  /** Like Count */
  likeCount: number;
  /** Bookmarked At */
  bookmarkedAt: string;
  /** Content */
  content: string;
  /** Comment Count */
  commentCount: number;
};
