/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Post Type
 */
export type GetBookmarkedPostsResponsePostsNodesItemContentSummaryType =
  (typeof GetBookmarkedPostsResponsePostsNodesItemContentSummaryType)[keyof typeof GetBookmarkedPostsResponsePostsNodesItemContentSummaryType];

export const GetBookmarkedPostsResponsePostsNodesItemContentSummaryType = {
  Short: 'SHORT',
  Long: 'LONG',
  Question: 'QUESTION',
} as const;
