/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetBookmarkedPostsResponsePostsNodesItemContentSummaryAuthor } from './GetBookmarkedPostsResponsePostsNodesItemContentSummaryAuthor';
import type { GetBookmarkedPostsResponsePostsNodesItemContentSummaryProject } from './GetBookmarkedPostsResponsePostsNodesItemContentSummaryProject';
import type { GetBookmarkedPostsResponsePostsNodesItemContentSummaryType } from './GetBookmarkedPostsResponsePostsNodesItemContentSummaryType';

/**
 * Post Summary
 */
export type GetBookmarkedPostsResponsePostsNodesItemContentSummary = {
  /** Creation Timestamp */
  createdAt: string;
  /** 작성자 정보 */
  author: GetBookmarkedPostsResponsePostsNodesItemContentSummaryAuthor;
  /** 소속 프로젝트 정보 */
  project?: GetBookmarkedPostsResponsePostsNodesItemContentSummaryProject;
  /** Post ID */
  id: number;
  /** Post Type */
  type: GetBookmarkedPostsResponsePostsNodesItemContentSummaryType;
  /**
   * Post Title
   * @nullable
   */
  title?: string | null;
  /** Post Slug */
  slug: string;
  /** Whether the requesting user is the author of this post */
  isAuthor: boolean;
  /** Whether the question post has been resolved */
  resolved: boolean;
};
