/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 요청자의 열람 수준 (FULL: 본문까지 열람, PREVIEW: 유료 게이트로 본문 잠김)
 * @nullable
 */
export type GetCollectionPostsResponsePostsNodesItemContentPostAccessLevel =
  | (typeof GetCollectionPostsResponsePostsNodesItemContentPostAccessLevel)[keyof typeof GetCollectionPostsResponsePostsNodesItemContentPostAccessLevel]
  | null;

export const GetCollectionPostsResponsePostsNodesItemContentPostAccessLevel = {
  Full: 'FULL',
  Preview: 'PREVIEW',
} as const;
