/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 컬렉션 범위 (PERSONAL: 개인, WORKSPACE: 프로젝트 소속)
 */
export type GetCollectionsResponseCollectionsItemScope =
  (typeof GetCollectionsResponseCollectionsItemScope)[keyof typeof GetCollectionsResponseCollectionsItemScope];

export const GetCollectionsResponseCollectionsItemScope = {
  Personal: 'PERSONAL',
  Workspace: 'WORKSPACE',
} as const;
