/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetCollectionsResponseMembershipsItem = {
  /**
   * 해당 컬렉션 안에서 이 게시글이 위치한 항목 ID (제거 시 사용)
   * @nullable
   */
  collectionPostId?: number | null;
  /**
   * 게시글을 담고 있는 컬렉션의 외부 식별자
   * @nullable
   */
  collectionExternalId?: string | null;
};
