/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetCollectionPostsResponsePostsNodesItemContentPostPreviewMediaItem =
  {
    /**
     * 미디어 ID
     * @nullable
     */
    id?: number | null;
    /**
     * 미디어 URL
     * @nullable
     */
    url?: string | null;
  };
