/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetCollectionPostsResponsePostsNodesItemContentPost } from './GetCollectionPostsResponsePostsNodesItemContentPost';

/**
 * Node Content
 */
export type GetCollectionPostsResponsePostsNodesItemContent = {
  /** 컬렉션 항목 ID (항목 제거 시 사용) */
  collectionPostId: number;
  /** 게시글 요약 (뷰어가 열람 가능한 경우에만 존재. 없으면 삭제·비공개로 열람 불가한 tombstone 이다. 본문 열람 수준은 post.accessLevel 로 구분한다) */
  post?: GetCollectionPostsResponsePostsNodesItemContentPost;
};
