/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetCollectionPostsResponsePostsNodesItemContentPostTagsItem = {
  /**
   * 요청자가 해당 태그를 팔로우하고 있는지 여부 (프로젝트 태그는 항상 false)
   * @nullable
   */
  isFollowing?: boolean | null;
  /**
   * 태그 이름
   * @nullable
   */
  name?: string | null;
  /**
   * 태그가 사용된 게시물 수
   * @nullable
   */
  postCount?: number | null;
  /**
   * 태그 설명
   * @nullable
   */
  description?: string | null;
  /**
   * 태그 ID
   * @nullable
   */
  id?: number | null;
  /**
   * 태그를 팔로우하는 사용자 수
   * @nullable
   */
  followerCount?: number | null;
  /**
   * 프로젝트 태그인 경우 해당 프로젝트의 핸들 (전역 태그인 경우 없음)
   * @nullable
   */
  projectHandle?: string | null;
};
