/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetCollectionsResponseCollectionsItem } from './GetCollectionsResponseCollectionsItem';

export interface GetCollectionsResponse {
  /** 컬렉션 목록 */
  collections: GetCollectionsResponseCollectionsItem[];
}
