/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetCollectionPostsResponsePosts } from './GetCollectionPostsResponsePosts';

export interface GetCollectionPostsResponse {
  /** 컬렉션 항목 페이지 */
  posts: GetCollectionPostsResponsePosts;
}
