/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 게시글 공개 범위
 * @nullable
 */
export type GetCollectionPostsResponsePostsNodesItemContentPostScope =
  | (typeof GetCollectionPostsResponsePostsNodesItemContentPostScope)[keyof typeof GetCollectionPostsResponsePostsNodesItemContentPostScope]
  | null;

export const GetCollectionPostsResponsePostsNodesItemContentPostScope = {
  Public: 'PUBLIC',
  Workspace: 'WORKSPACE',
} as const;
