/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetCollectionPostsResponsePostsNodesItemContent } from './GetCollectionPostsResponsePostsNodesItemContent';

export type GetCollectionPostsResponsePostsNodesItem = {
  /** Node Cursor */
  cursor: string;
  /** Node Content */
  content: GetCollectionPostsResponsePostsNodesItemContent;
};
