/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Post Status
 * @nullable
 */
export type GetCollectionPostsResponsePostsNodesItemContentPostStatus =
  | (typeof GetCollectionPostsResponsePostsNodesItemContentPostStatus)[keyof typeof GetCollectionPostsResponsePostsNodesItemContentPostStatus]
  | null;

export const GetCollectionPostsResponsePostsNodesItemContentPostStatus = {
  Draft: 'DRAFT',
  Published: 'PUBLISHED',
} as const;
