/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface GetChannelTalkIdentityResponse {
  /**
   * HMAC-SHA256 of memberId. Null when the server has no secret key configured — the client must then boot Channel Talk anonymously.
   * @nullable
   */
  memberHash?: string | null;
  /** Channel Talk member identifier of the authenticated user */
  memberId: string;
}
