/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetCollectionPostsResponsePostsNodesItem } from './GetCollectionPostsResponsePostsNodesItem';
import type { GetCollectionPostsResponsePostsPageInfo } from './GetCollectionPostsResponsePostsPageInfo';

/**
 * 컬렉션 항목 페이지
 */
export type GetCollectionPostsResponsePosts = {
  /** Nodes */
  nodes: GetCollectionPostsResponsePostsNodesItem[];
  /** Page Info */
  pageInfo: GetCollectionPostsResponsePostsPageInfo;
};
