/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetConnectionsResponseConnectionsNodesItemContent } from './GetConnectionsResponseConnectionsNodesItemContent';

export type GetConnectionsResponseConnectionsNodesItem = {
  /** Node Cursor */
  cursor: string;
  /** Node Content */
  content: GetConnectionsResponseConnectionsNodesItemContent;
};
