/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetCollectionsResponseCollectionsItemScope } from './GetCollectionsResponseCollectionsItemScope';

export type GetCollectionsResponseCollectionsItem = {
  /**
   * postHandle 쿼리 파라미터가 주어졌을 때, 해당 게시글이 이 컬렉션에 담겨 있는지 여부 (없으면 생략)
   * @nullable
   */
  containsPost?: boolean | null;
  /** 컬렉션 범위 (PERSONAL: 개인, WORKSPACE: 프로젝트 소속) */
  scope: GetCollectionsResponseCollectionsItemScope;
  /** 컬렉션 생성자 ID */
  creatorId: number;
  /** 컬렉션 이름 */
  name: string;
  /** 컬렉션에 담긴 항목 수 */
  postCount: number;
  /** 공개 여부 */
  isPublic: boolean;
  /**
   * 컬렉션 설명
   * @nullable
   */
  description?: string | null;
  /** 컬렉션 외부 식별자 */
  externalId: string;
  /**
   * 소속 프로젝트 핸들 (WORKSPACE 범위인 경우, PERSONAL 이면 없음)
   * @nullable
   */
  projectHandle?: string | null;
};
