/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetConnectionsResponseConnections } from './GetConnectionsResponseConnections';

export interface GetConnectionsResponse {
  connections?: GetConnectionsResponseConnections;
}
