/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Post Type
 * @nullable
 */
export type GetCollectionPostsResponsePostsNodesItemContentPostType =
  | (typeof GetCollectionPostsResponsePostsNodesItemContentPostType)[keyof typeof GetCollectionPostsResponsePostsNodesItemContentPostType]
  | null;

export const GetCollectionPostsResponsePostsNodesItemContentPostType = {
  Short: 'SHORT',
  Long: 'LONG',
  Question: 'QUESTION',
} as const;
