/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetCommentsResponseCommentsNodesItemContentAuthor } from './GetCommentsResponseCommentsNodesItemContentAuthor';

/**
 * Node Content
 */
export type GetCommentsResponseCommentsNodesItemContent = {
  /** Creation timestamp */
  createdAt: string;
  /** Whether the author is the post author */
  isPostAuthor: boolean;
  /** Is deleted */
  isDeleted: boolean;
  /** Comment author */
  author: GetCommentsResponseCommentsNodesItemContentAuthor;
  /** Is accepted */
  isAccepted: boolean;
  /** Whether the requester can delete this comment */
  canDelete: boolean;
  /** Like count */
  likeCount: number;
  /** Comment ID */
  id: number;
  /** Whether the requester liked this comment */
  liked: boolean;
  /**
   * Comment content
   * @nullable
   */
  content?: string | null;
  /** Update timestamp */
  updatedAt: string;
};
