/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 작성자 정보
 */
export type GetCollectionPostsResponsePostsNodesItemContentPostAuthor = {
  /**
   * 탈퇴한 사용자인지 여부
   * @nullable
   */
  isDeleted?: boolean | null;
  /**
   * 유저 이름
   * @nullable
   */
  name?: string | null;
  /**
   * 유저 핸들
   * @nullable
   */
  handle?: string | null;
  /**
   * 유저 프로필 이미지 URL
   * @nullable
   */
  profileImageUrl?: string | null;
};
