/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 프로젝트 정보
 */
export type GetMyProjectInvitationsResponseInvitationsItemProject = {
  /**
   * 프로젝트 웹사이트
   * @nullable
   */
  website?: string | null;
  /** 프로젝트 이름 */
  name: string;
  /** 공개 여부 */
  isPublic: boolean;
  /**
   * 프로젝트 설명
   * @nullable
   */
  description?: string | null;
  /** 프로젝트 핸들 */
  handle: string;
};
