/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetMyProjectJoinRequestsResponseJoinRequestsItemProject } from './GetMyProjectJoinRequestsResponseJoinRequestsItemProject';

export type GetMyProjectJoinRequestsResponseJoinRequestsItem = {
  /** 가입 요청 시각 */
  createdAt: string;
  /** 프로젝트 정보 */
  project: GetMyProjectJoinRequestsResponseJoinRequestsItemProject;
  /** 가입 요청 ID */
  id: number;
};
