/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetMyProjectJoinRequestsResponseJoinRequestsItem } from './GetMyProjectJoinRequestsResponseJoinRequestsItem';

export interface GetMyProjectJoinRequestsResponse {
  /** 가입 요청 목록 */
  joinRequests: GetMyProjectJoinRequestsResponseJoinRequestsItem[];
}
