/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetNotificationsResponseNotifications } from './GetNotificationsResponseNotifications';

export interface GetNotificationsResponse {
  /** Total unread notification count */
  unreadCount: number;
  /** Paginated Result */
  notifications: GetNotificationsResponseNotifications;
}
