/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetNotificationsResponseNotificationsContentItem } from './GetNotificationsResponseNotificationsContentItem';
import type { GetNotificationsResponseNotificationsPageInfo } from './GetNotificationsResponseNotificationsPageInfo';

export type GetNotificationsResponseNotifications = {
  /** Page Info */
  pageInfo: GetNotificationsResponseNotificationsPageInfo;
  /** Content */
  content: GetNotificationsResponseNotificationsContentItem[];
};
