/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Pagination request info
 */
export type GetNotificationsResponseNotificationsPageable = {
  [key: string]: unknown;
};
