/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetNotificationsResponseNotificationsContentItemActor = {
  /**
   * Actor name
   * @nullable
   */
  name?: string | null;
  /**
   * Actor handle
   * @nullable
   */
  handle?: string | null;
  /**
   * Actor profile image URL
   * @nullable
   */
  profileImageUrl?: string | null;
};
