/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostResponseSummaryAuthor } from './GetPostResponseSummaryAuthor';
import type { GetPostResponseSummaryProject } from './GetPostResponseSummaryProject';
import type { GetPostResponseSummaryType } from './GetPostResponseSummaryType';

/**
 * 포스트 정보
 */
export type GetPostResponseSummary = {
  /** Creation Timestamp */
  createdAt: string;
  /** 작성자 정보 */
  author: GetPostResponseSummaryAuthor;
  /** 소속 프로젝트 정보 */
  project?: GetPostResponseSummaryProject;
  /** Post ID */
  id: number;
  /** Post Type */
  type: GetPostResponseSummaryType;
  /** Post Slug */
  slug: string;
  /** Whether the question post has been resolved */
  resolved: boolean;
};
