/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostsResponsePostsItemAccessLevel } from './GetPostsResponsePostsItemAccessLevel';
import type { GetPostsResponsePostsItemAuthor } from './GetPostsResponsePostsItemAuthor';
import type { GetPostsResponsePostsItemPreviewMediaItem } from './GetPostsResponsePostsItemPreviewMediaItem';
import type { GetPostsResponsePostsItemProject } from './GetPostsResponsePostsItemProject';
import type { GetPostsResponsePostsItemScope } from './GetPostsResponsePostsItemScope';
import type { GetPostsResponsePostsItemStatus } from './GetPostsResponsePostsItemStatus';
import type { GetPostsResponsePostsItemTagsItem } from './GetPostsResponsePostsItemTagsItem';
import type { GetPostsResponsePostsItemType } from './GetPostsResponsePostsItemType';

export type GetPostsResponsePostsItem = {
  /** 게시물 내용의 일반 텍스트 미리보기 */
  preview: string;
  /** 게시물 본문의 단어 수 */
  wordCount: number;
  /** 요청자의 열람 수준 (FULL: 본문까지 열람, PREVIEW: 유료 게이트로 본문 잠김) */
  accessLevel: GetPostsResponsePostsItemAccessLevel;
  /**
   * 게시물 커버 이미지 URL (없으면 없음)
   * @nullable
   */
  coverImageUrl?: string | null;
  /** Whether the current user bookmarked this post */
  bookmarked: boolean;
  /** 작성자 정보 */
  author: GetPostsResponsePostsItemAuthor;
  /** 소속 프로젝트 정보 */
  project?: GetPostsResponsePostsItemProject;
  /** Number of Likes */
  likeCount: number;
  /** Post Type */
  type: GetPostsResponsePostsItemType;
  /**
   * Post Title
   * @nullable
   */
  title?: string | null;
  /** Whether the current user liked this post */
  liked: boolean;
  /** 게시물에 달린 태그 목록 */
  tags: GetPostsResponsePostsItemTagsItem[];
  /** Number of Comments */
  commentCount: number;
  /** Whether the requesting user is the author of this post */
  isAuthor: boolean;
  /** Creation Timestamp */
  createdAt: string;
  /** 게시글이 어떤 시리즈에 속해 있는지 여부 */
  isSeriesPost: boolean;
  /** 게시글 공개 범위 */
  scope: GetPostsResponsePostsItemScope;
  /** 게시물에 첨부된 전체 미디어 수 */
  mediaCount: number;
  /** Post ID */
  id: number;
  /** 미리보기용 첨부 미디어 목록 (최대 3개) */
  previewMedia: GetPostsResponsePostsItemPreviewMediaItem[];
  /** Post Slug */
  slug: string;
  /** Last Updated Timestamp */
  updatedAt: string;
  /** Whether the question post has been resolved */
  resolved: boolean;
  /** Post Status */
  status: GetPostsResponsePostsItemStatus;
};
