/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostSeriesListResponseSeriesItemScope } from './GetPostSeriesListResponseSeriesItemScope';

export type GetPostSeriesListResponseSeriesItem = {
  /** 시리즈 공개 범위 (PUBLIC: 개인 시리즈, WORKSPACE: 프로젝트 시리즈) */
  scope: GetPostSeriesListResponseSeriesItemScope;
  /** 시리즈 생성자 ID */
  creatorId: number;
  /** 시리즈 이름 */
  name: string;
  /** 시리즈에 포함된 게시글 수 */
  postCount: number;
  /** 시리즈 외부 식별자 */
  externalId: string;
  /**
   * 프로젝트 시리즈인 경우 소속 프로젝트 핸들 (개인 시리즈인 경우 없음)
   * @nullable
   */
  projectHandle?: string | null;
};
