/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 프로젝트 참여 정책
 */
export type GetProjectsResponseProjectsItemJoinPolicy =
  (typeof GetProjectsResponseProjectsItemJoinPolicy)[keyof typeof GetProjectsResponseProjectsItemJoinPolicy];

export const GetProjectsResponseProjectsItemJoinPolicy = {
  Open: 'OPEN',
  Request: 'REQUEST',
  Invite: 'INVITE',
} as const;
