/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostResponseContentMediaItem } from './GetPostResponseContentMediaItem';

/**
 * 게시글 본문. summary.accessLevel 이 PREVIEW(유료 게이트)이면 이 필드 자체가 응답에서 빠진다
 */
export type GetPostResponseContent = {
  /** Post Content JSON */
  json: string;
  /** Media attached to the post */
  media: GetPostResponseContentMediaItem[];
};
