/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostResponseContent } from './GetPostResponseContent';
import type { GetPostResponseSummary } from './GetPostResponseSummary';

export interface GetPostResponse {
  /** 포스트 정보 */
  summary: GetPostResponseSummary;
  /** 게시글 본문. summary.accessLevel 이 PREVIEW(유료 게이트)이면 이 필드 자체가 응답에서 빠진다 */
  content?: GetPostResponseContent;
}
