/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostReportsResponseReports } from './GetPostReportsResponseReports';

export interface GetPostReportsResponse {
  reports?: GetPostReportsResponseReports;
}
