/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetProjectJoinRequestsResponseJoinRequestsItem } from './GetProjectJoinRequestsResponseJoinRequestsItem';

export interface GetProjectJoinRequestsResponse {
  /** 가입 요청 목록 */
  joinRequests: GetProjectJoinRequestsResponseJoinRequestsItem[];
}
