/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostsResponsePostsItem } from './GetPostsResponsePostsItem';

export interface GetPostsResponse {
  /** 검색 결과 게시글 목록 */
  posts: GetPostsResponsePostsItem[];
}
