/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostSeriesResponsePostsItem } from './GetPostSeriesResponsePostsItem';
import type { GetPostSeriesResponseSeries } from './GetPostSeriesResponseSeries';

export interface GetPostSeriesResponse {
  /**
   * 조회 기준 게시글의 시리즈-게시글 연결 ID (시리즈에 속하지 않으면 없음)
   * @nullable
   */
  currentSeriesPostId?: number | null;
  /** 게시글이 속한 시리즈 (어떤 시리즈에도 속하지 않으면 없음) */
  series?: GetPostSeriesResponseSeries;
  /** 시리즈에 포함된 게시글 목록 (순서대로, 시리즈에 속하지 않으면 빈 배열) */
  posts: GetPostSeriesResponsePostsItem[];
}
