/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetProjectCollectionsParams = {
  /**
   * 주어지면 이 게시글(slug)을 담고 있는 컬렉션의 멤버십을 memberships 로 표시한다.
   */
  postHandle?: string;
};
