/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostRecommendationsResponsePostsNodesItemContentSummaryAuthor } from './GetPostRecommendationsResponsePostsNodesItemContentSummaryAuthor';
import type { GetPostRecommendationsResponsePostsNodesItemContentSummaryProject } from './GetPostRecommendationsResponsePostsNodesItemContentSummaryProject';
import type { GetPostRecommendationsResponsePostsNodesItemContentSummaryType } from './GetPostRecommendationsResponsePostsNodesItemContentSummaryType';

/**
 * Post Summary
 */
export type GetPostRecommendationsResponsePostsNodesItemContentSummary = {
  /** Creation Timestamp */
  createdAt: string;
  /** 작성자 정보 */
  author: GetPostRecommendationsResponsePostsNodesItemContentSummaryAuthor;
  /** 소속 프로젝트 정보 */
  project?: GetPostRecommendationsResponsePostsNodesItemContentSummaryProject;
  /** Post ID */
  id: number;
  /** Post Type */
  type: GetPostRecommendationsResponsePostsNodesItemContentSummaryType;
  /** Post Slug */
  slug: string;
  /** Whether the question post has been resolved */
  resolved: boolean;
};
