/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Post Scope
 */
export type GetPostsResponsePostsNodesItemContentSummaryScope =
  (typeof GetPostsResponsePostsNodesItemContentSummaryScope)[keyof typeof GetPostsResponsePostsNodesItemContentSummaryScope];

export const GetPostsResponsePostsNodesItemContentSummaryScope = {
  Public: 'PUBLIC',
  Workspace: 'WORKSPACE',
} as const;
