/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostsResponsePostsNodesItemContentSummary } from './GetPostsResponsePostsNodesItemContentSummary';

/**
 * Node Content
 */
export type GetPostsResponsePostsNodesItemContent = {
  /** Post Summary */
  summary: GetPostsResponsePostsNodesItemContentSummary;
  /** Post Content */
  content: string;
};
