/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Post Status
 */
export type GetPostsResponsePostsItemStatus =
  (typeof GetPostsResponsePostsItemStatus)[keyof typeof GetPostsResponsePostsItemStatus];

export const GetPostsResponsePostsItemStatus = {
  Draft: 'DRAFT',
  Published: 'PUBLISHED',
} as const;
