/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 시리즈 공개 범위 (PUBLIC: 개인 시리즈, WORKSPACE: 프로젝트 시리즈)
 */
export type GetPostSeriesListResponseSeriesItemScope =
  (typeof GetPostSeriesListResponseSeriesItemScope)[keyof typeof GetPostSeriesListResponseSeriesItemScope];

export const GetPostSeriesListResponseSeriesItemScope = {
  Public: 'PUBLIC',
  Workspace: 'WORKSPACE',
} as const;
