/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 프로젝트 참여 정책
 * @nullable
 */
export type GetPostsResponsePostsItemProjectJoinPolicy =
  | (typeof GetPostsResponsePostsItemProjectJoinPolicy)[keyof typeof GetPostsResponsePostsItemProjectJoinPolicy]
  | null;

export const GetPostsResponsePostsItemProjectJoinPolicy = {
  Open: 'OPEN',
  Request: 'REQUEST',
  Invite: 'INVITE',
} as const;
