/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Post Scope
 */
export type GetPostRecommendationsResponsePostsNodesItemContentSummaryScope =
  (typeof GetPostRecommendationsResponsePostsNodesItemContentSummaryScope)[keyof typeof GetPostRecommendationsResponsePostsNodesItemContentSummaryScope];

export const GetPostRecommendationsResponsePostsNodesItemContentSummaryScope = {
  Public: 'PUBLIC',
  Workspace: 'WORKSPACE',
} as const;
