/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Node Content
 */
export type GetProjectFollowersResponseFollowersNodesItemContent = {
  /** User Name */
  name: string;
  /** User Handle */
  handle: string;
  /** User ID */
  userId: string;
};
