/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetProjectJoinRequestsResponseJoinRequestsItemRequester } from './GetProjectJoinRequestsResponseJoinRequestsItemRequester';

export type GetProjectJoinRequestsResponseJoinRequestsItem = {
  /** 가입 요청한 유저 정보 */
  requester: GetProjectJoinRequestsResponseJoinRequestsItemRequester;
  /** 가입 요청 시각 */
  createdAt: string;
  /** 가입 요청 ID */
  id: number;
};
