/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetPostSeriesResponsePostsItem = {
  /** 시리즈-게시글 연결 ID (순서 변경/삭제 시 사용) */
  seriesPostId: number;
  /** 시리즈 내 게시글 위치 (1부터 시작) */
  position: number;
  /**
   * 게시글 제목 (열람 권한이 없거나 삭제된 경우 없음)
   * @nullable
   */
  title?: string | null;
};
