/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostRecommendationsResponsePostsNodesItemContentSummaryAuthor } from './GetPostRecommendationsResponsePostsNodesItemContentSummaryAuthor';
import type { GetPostRecommendationsResponsePostsNodesItemContentSummaryProject } from './GetPostRecommendationsResponsePostsNodesItemContentSummaryProject';
import type { GetPostRecommendationsResponsePostsNodesItemContentSummaryScope } from './GetPostRecommendationsResponsePostsNodesItemContentSummaryScope';
import type { GetPostRecommendationsResponsePostsNodesItemContentSummaryStatus } from './GetPostRecommendationsResponsePostsNodesItemContentSummaryStatus';
import type { GetPostRecommendationsResponsePostsNodesItemContentSummaryType } from './GetPostRecommendationsResponsePostsNodesItemContentSummaryType';

/**
 * Post Summary
 */
export type GetPostRecommendationsResponsePostsNodesItemContentSummary = {
  /** 작성자 정보 */
  author: GetPostRecommendationsResponsePostsNodesItemContentSummaryAuthor;
  /** 소속 프로젝트 정보 */
  project?: GetPostRecommendationsResponsePostsNodesItemContentSummaryProject;
  /** Number of Likes */
  likeCount: number;
  /** Post Type */
  type: GetPostRecommendationsResponsePostsNodesItemContentSummaryType;
  /**
   * Post Title
   * @nullable
   */
  title?: string | null;
  /** Number of Comments */
  commentCount: number;
  /** Whether the requesting user is the author of this post */
  isAuthor: boolean;
  /** Creation Timestamp */
  createdAt: string;
  /** Post Scope */
  scope: GetPostRecommendationsResponsePostsNodesItemContentSummaryScope;
  /** Post ID */
  id: number;
  /** Post Slug */
  slug: string;
  /** Whether the question post has been resolved */
  resolved: boolean;
  /** Post Status */
  status: GetPostRecommendationsResponsePostsNodesItemContentSummaryStatus;
};
