/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 시리즈 공개 범위 (PUBLIC: 개인 시리즈, WORKSPACE: 프로젝트 시리즈)
 * @nullable
 */
export type GetPostSeriesResponseSeriesScope =
  | (typeof GetPostSeriesResponseSeriesScope)[keyof typeof GetPostSeriesResponseSeriesScope]
  | null;

export const GetPostSeriesResponseSeriesScope = {
  Public: 'PUBLIC',
  Workspace: 'WORKSPACE',
} as const;
