/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostSeriesResponseSeriesScope } from './GetPostSeriesResponseSeriesScope';

/**
 * 게시글이 속한 시리즈 (어떤 시리즈에도 속하지 않으면 없음)
 */
export type GetPostSeriesResponseSeries = {
  /**
   * 시리즈 공개 범위 (PUBLIC: 개인 시리즈, WORKSPACE: 프로젝트 시리즈)
   * @nullable
   */
  scope?: GetPostSeriesResponseSeriesScope;
  /**
   * 시리즈 생성자 ID
   * @nullable
   */
  creatorId?: number | null;
  /**
   * 시리즈 이름
   * @nullable
   */
  name?: string | null;
  /**
   * 시리즈에 포함된 게시글 수
   * @nullable
   */
  postCount?: number | null;
  /**
   * 시리즈 외부 식별자
   * @nullable
   */
  externalId?: string | null;
  /**
   * 프로젝트 시리즈인 경우 소속 프로젝트 핸들 (개인 시리즈인 경우 없음)
   * @nullable
   */
  projectHandle?: string | null;
};
