/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostSeriesListResponseSeriesItem } from './GetPostSeriesListResponseSeriesItem';

export interface GetPostSeriesListResponse {
  /** 시리즈 목록 */
  series: GetPostSeriesListResponseSeriesItem[];
}
