/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 게시글 공개 범위
 */
export type GetPostsResponsePostsItemScope =
  (typeof GetPostsResponsePostsItemScope)[keyof typeof GetPostsResponsePostsItemScope];

export const GetPostsResponsePostsItemScope = {
  Public: 'PUBLIC',
  Workspace: 'WORKSPACE',
} as const;
