/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostsResponsePostsNodesItemContentSummaryAuthor } from './GetPostsResponsePostsNodesItemContentSummaryAuthor';
import type { GetPostsResponsePostsNodesItemContentSummaryProject } from './GetPostsResponsePostsNodesItemContentSummaryProject';
import type { GetPostsResponsePostsNodesItemContentSummaryType } from './GetPostsResponsePostsNodesItemContentSummaryType';

/**
 * Post Summary
 */
export type GetPostsResponsePostsNodesItemContentSummary = {
  /** Creation Timestamp */
  createdAt: string;
  /** 작성자 정보 */
  author: GetPostsResponsePostsNodesItemContentSummaryAuthor;
  /** 소속 프로젝트 정보 */
  project?: GetPostsResponsePostsNodesItemContentSummaryProject;
  /** Number of Likes */
  likeCount: number;
  /** Post ID */
  id: number;
  /** Post Type */
  type: GetPostsResponsePostsNodesItemContentSummaryType;
  /**
   * Post Title
   * @nullable
   */
  title?: string | null;
  /** Post Slug */
  slug: string;
  /** Number of Comments */
  commentCount: number;
  /** Whether the requesting user is the author of this post */
  isAuthor: boolean;
  /** Whether the question post has been resolved */
  resolved: boolean;
};
