/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Post Status
 */
export type GetPostRecommendationsResponsePostsNodesItemContentSummaryStatus =
  (typeof GetPostRecommendationsResponsePostsNodesItemContentSummaryStatus)[keyof typeof GetPostRecommendationsResponsePostsNodesItemContentSummaryStatus];

export const GetPostRecommendationsResponsePostsNodesItemContentSummaryStatus =
  {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
  } as const;
