/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostResponseContent } from './GetPostResponseContent';
import type { GetPostResponseSummary } from './GetPostResponseSummary';

export interface GetPostResponse {
  /** 포스트 정보 */
  summary: GetPostResponseSummary;
  /** Whether the current user bookmarked this post */
  bookmarked: boolean;
  /** Post Content */
  content: GetPostResponseContent;
}
