/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Post Scope
 */
export type GetPostResponseSummaryScope =
  (typeof GetPostResponseSummaryScope)[keyof typeof GetPostResponseSummaryScope];

export const GetPostResponseSummaryScope = {
  Public: 'PUBLIC',
  Workspace: 'WORKSPACE',
} as const;
