/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetUserCollectionsParams = {
  /**
   * 주어지면 각 컬렉션이 이 게시글(slug)을 담고 있는지 containsPost 로 표시한다.
   */
  postHandle?: string;
};
