/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { NewCommentPayloadType } from './NewCommentPayloadType';

export interface NewCommentPayload {
  type: NewCommentPayloadType;
  actorHandle: string;
  actorName: string;
  postTitle: string;
  postSlug: string;
}
