/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { NewFollowerPayloadType } from './NewFollowerPayloadType';

export interface NewFollowerPayload {
  type: NewFollowerPayloadType;
  actorHandle: string;
  actorName: string;
}
