/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type NewFollowerPayloadType =
  (typeof NewFollowerPayloadType)[keyof typeof NewFollowerPayloadType];

export const NewFollowerPayloadType = {
  NewFollower: 'NEW_FOLLOWER',
} as const;
