/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { NewMessagePayloadType } from './NewMessagePayloadType';

export interface NewMessagePayload {
  type: NewMessagePayloadType;
  actorHandle: string;
  actorName: string;
  conversationId: number;
  messagePreview: string;
}
