/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type NewMessagePayloadType =
  (typeof NewMessagePayloadType)[keyof typeof NewMessagePayloadType];

export const NewMessagePayloadType = {
  NewMessage: 'NEW_MESSAGE',
} as const;
