/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { PaginatedGetPostsResponsePostsNodesItem } from './PaginatedGetPostsResponsePostsNodesItem';
import type { PaginatedGetPostsResponsePostsPageInfo } from './PaginatedGetPostsResponsePostsPageInfo';

export type PaginatedGetPostsResponsePosts = {
  /** Nodes */
  nodes: PaginatedGetPostsResponsePostsNodesItem[];
  /** Page Info */
  pageInfo: PaginatedGetPostsResponsePostsPageInfo;
};
