/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { PaginatedGetPostsResponsePostsNodesItemContent } from './PaginatedGetPostsResponsePostsNodesItemContent';

export type PaginatedGetPostsResponsePostsNodesItem = {
  /** Node Cursor */
  cursor: string;
  /** Node Content */
  content: PaginatedGetPostsResponsePostsNodesItemContent;
};
