/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { ProjectJoinRequestDeclinedPayloadType } from './ProjectJoinRequestDeclinedPayloadType';

export interface ProjectJoinRequestDeclinedPayload {
  type: ProjectJoinRequestDeclinedPayloadType;
  projectHandle: string;
  projectName: string;
}
