/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type ProjectInvitationPayloadType =
  (typeof ProjectInvitationPayloadType)[keyof typeof ProjectInvitationPayloadType];

export const ProjectInvitationPayloadType = {
  ProjectInvitation: 'PROJECT_INVITATION',
} as const;
