/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type ProjectJoinRequestApprovedPayloadType =
  (typeof ProjectJoinRequestApprovedPayloadType)[keyof typeof ProjectJoinRequestApprovedPayloadType];

export const ProjectJoinRequestApprovedPayloadType = {
  ProjectJoinRequestApproved: 'PROJECT_JOIN_REQUEST_APPROVED',
} as const;
