/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { ProjectInvitationAcceptedPayloadType } from './ProjectInvitationAcceptedPayloadType';

export interface ProjectInvitationAcceptedPayload {
  type: ProjectInvitationAcceptedPayloadType;
  actorHandle: string;
  actorName: string;
  projectHandle: string;
  projectName: string;
}
