/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type ProjectInvitationDeclinedPayloadType =
  (typeof ProjectInvitationDeclinedPayloadType)[keyof typeof ProjectInvitationDeclinedPayloadType];

export const ProjectInvitationDeclinedPayloadType = {
  ProjectInvitationDeclined: 'PROJECT_INVITATION_DECLINED',
} as const;
