/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { ProjectJoinRequestPayloadType } from './ProjectJoinRequestPayloadType';

export interface ProjectJoinRequestPayload {
  type: ProjectJoinRequestPayloadType;
  actorHandle: string;
  actorName: string;
  projectHandle: string;
  projectName: string;
}
