/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type ProjectInvitationAcceptedPayloadType =
  (typeof ProjectInvitationAcceptedPayloadType)[keyof typeof ProjectInvitationAcceptedPayloadType];

export const ProjectInvitationAcceptedPayloadType = {
  ProjectInvitationAccepted: 'PROJECT_INVITATION_ACCEPTED',
} as const;
