/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type ProjectJoinRequestDeclinedPayloadType =
  (typeof ProjectJoinRequestDeclinedPayloadType)[keyof typeof ProjectJoinRequestDeclinedPayloadType];

export const ProjectJoinRequestDeclinedPayloadType = {
  ProjectJoinRequestDeclined: 'PROJECT_JOIN_REQUEST_DECLINED',
} as const;
