/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { ProjectInvitationPayloadType } from './ProjectInvitationPayloadType';

export interface ProjectInvitationPayload {
  type: ProjectInvitationPayloadType;
  actorHandle: string;
  actorName: string;
  projectHandle: string;
  projectName: string;
  token: string;
}
