/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { PromotionResponseListItem } from './PromotionResponseListItem';

export type PromotionResponseList = PromotionResponseListItem[];
