/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { PromotionSignupResponseAttachment } from './PromotionSignupResponseAttachment';

export interface PromotionSignupResponse {
  /** 신청 시각 */
  createdAt: string;
  /** 제출한 데이터 */
  attachment: PromotionSignupResponseAttachment;
}
