/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 제출한 데이터
 */
export type PromotionSignupResponseAttachment = {
  /**
   * 등록한 전화번호
   * @nullable
   */
  phoneNumber?: string | null;
};
