/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface ReorderPostSeriesPostRequest {
  /** 이동할 새 위치 (1부터 시작) */
  position: number;
}
