/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type SearchAdminProjectParams = {
  /**
   * 검색어 (프로젝트 이름, 핸들)
   */
  query: string;
};
