/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { SearchPostsResponsePostsItemSummaryAuthor } from './SearchPostsResponsePostsItemSummaryAuthor';
import type { SearchPostsResponsePostsItemSummaryProject } from './SearchPostsResponsePostsItemSummaryProject';
import type { SearchPostsResponsePostsItemSummaryType } from './SearchPostsResponsePostsItemSummaryType';

/**
 * Post Summary
 */
export type SearchPostsResponsePostsItemSummary = {
  /** Creation Timestamp */
  createdAt: string;
  /** 작성자 정보 */
  author: SearchPostsResponsePostsItemSummaryAuthor;
  /** 소속 프로젝트 정보 */
  project?: SearchPostsResponsePostsItemSummaryProject;
  /** Post ID */
  id: number;
  /** Post Type */
  type: SearchPostsResponsePostsItemSummaryType;
  /** Post Slug */
  slug: string;
  /** Whether the question post has been resolved */
  resolved: boolean;
};
