/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface UpdatePostRequest {
  /** 일반 텍스트 콘텐츠 */
  text: string;
  /** Content */
  content: string;
}
