/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { UpdatePromotionRequestFieldsItemType } from './UpdatePromotionRequestFieldsItemType';

export type UpdatePromotionRequestFieldsItem = {
  /** 필드 라벨 */
  label: string;
  /** 필드 입력 타입 */
  type: UpdatePromotionRequestFieldsItemType;
  /** 필수 여부 */
  required: boolean;
  /** 필드 키 */
  key: string;
};
