/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface UpdatePostSeriesRequest {
  /**
   * 수정할 시리즈 이름 (null 이면 기존 이름 유지, 최대 255자)
   * @nullable
   */
  name?: string | null;
}
