/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { UpdatePromotionRequestFieldsItem } from './UpdatePromotionRequestFieldsItem';

export interface UpdatePromotionRequest {
  /** 연결된 게시글의 슬러그. 이미 생성된 게시글이어야 합니다. */
  postSlug: string;
  /** 신청 시 수집할 필드 목록. 전체 교체됩니다. */
  fields: UpdatePromotionRequestFieldsItem[];
  /** 연결된 게시글이 속한 프로젝트 핸들 */
  projectHandle: string;
}
