/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 필드 입력 타입
 */
export type UpdatePromotionRequestFieldsItemType =
  (typeof UpdatePromotionRequestFieldsItemType)[keyof typeof UpdatePromotionRequestFieldsItemType];

export const UpdatePromotionRequestFieldsItemType = {
  Text: 'TEXT',
  PhoneNumber: 'PHONE_NUMBER',
  Checkbox: 'CHECKBOX',
} as const;
