/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateNotificationPreferencesRequest {
  /** Whether in-app notifications should be enabled */
  inAppEnabled: boolean;
}
