/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface UploadMediaResponse {
  /** Pre-signed Upload URL */
  uploadUrl: string;
  /** Media ID */
  mediaId: string;
  /** Content-Type header the upload must send, signed into the URL */
  contentType: string;
  /** Expiration Time */
  expiresAt: string;
}
