/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type WelcomePayloadType =
  (typeof WelcomePayloadType)[keyof typeof WelcomePayloadType];

export const WelcomePayloadType = {
  Welcome: 'WELCOME',
} as const;
