/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  AddPostToPostSeriesRequest,
  CreatePostSeriesRequest,
  CreatePostSeriesResponse,
  GetPostSeriesListResponse,
  GetPostSeriesResponse,
  ReorderPostSeriesPostRequest,
  UpdatePostSeriesRequest,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getMyPostSeriesResponse200 = {
  data: GetPostSeriesListResponse;
  status: 200;
};

export type getMyPostSeriesResponseSuccess = getMyPostSeriesResponse200 & {
  headers: Headers;
};
export type getMyPostSeriesResponse = getMyPostSeriesResponseSuccess;

export const getGetMyPostSeriesUrl = () => {
  return `/me/series`;
};

/**
 * 로그인 사용자 본인의 개인 시리즈 목록을 조회합니다.
 * @summary Get My Post Series
 */
export const getMyPostSeries = async (
  options?: RequestInit,
): Promise<getMyPostSeriesResponse> => {
  return api<getMyPostSeriesResponse>(getGetMyPostSeriesUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getGetMyPostSeriesQueryKey = () => {
  return [`/me/series`] as const;
};

export const getGetMyPostSeriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getMyPostSeries>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getMyPostSeries>>, TError, TData>
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMyPostSeriesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyPostSeries>>> = ({
    signal,
  }) => getMyPostSeries({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMyPostSeries>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMyPostSeriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMyPostSeries>>
>;
export type GetMyPostSeriesQueryError = ErrorType<unknown>;

export function useGetMyPostSeries<
  TData = Awaited<ReturnType<typeof getMyPostSeries>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyPostSeries>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyPostSeries>>,
          TError,
          Awaited<ReturnType<typeof getMyPostSeries>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPostSeries<
  TData = Awaited<ReturnType<typeof getMyPostSeries>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyPostSeries>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyPostSeries>>,
          TError,
          Awaited<ReturnType<typeof getMyPostSeries>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMyPostSeries<
  TData = Awaited<ReturnType<typeof getMyPostSeries>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyPostSeries>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get My Post Series
 */

export function useGetMyPostSeries<
  TData = Awaited<ReturnType<typeof getMyPostSeries>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMyPostSeries>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMyPostSeriesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getSeriesForPostResponse200 = {
  data: GetPostSeriesResponse;
  status: 200;
};

export type getSeriesForPostResponseSuccess = getSeriesForPostResponse200 & {
  headers: Headers;
};
export type getSeriesForPostResponse = getSeriesForPostResponseSuccess;

export const getGetSeriesForPostUrl = (slug: string) => {
  return `/posts/${slug}/series`;
};

/**
 * 게시글이 속한 시리즈와 그 시리즈의 게시글 목록을 조회합니다.
 * @summary Get Series For Post
 */
export const getSeriesForPost = async (
  slug: string,
  options?: RequestInit,
): Promise<getSeriesForPostResponse> => {
  return api<getSeriesForPostResponse>(getGetSeriesForPostUrl(slug), {
    ...options,
    method: 'GET',
  });
};

export const getGetSeriesForPostQueryKey = (slug: string) => {
  return [`/posts/${slug}/series`] as const;
};

export const getGetSeriesForPostQueryOptions = <
  TData = Awaited<ReturnType<typeof getSeriesForPost>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSeriesForPost>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSeriesForPostQueryKey(slug);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSeriesForPost>>
  > = ({ signal }) => getSeriesForPost(slug, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: slug !== null && slug !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSeriesForPost>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSeriesForPostQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSeriesForPost>>
>;
export type GetSeriesForPostQueryError = ErrorType<unknown>;

export function useGetSeriesForPost<
  TData = Awaited<ReturnType<typeof getSeriesForPost>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSeriesForPost>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSeriesForPost>>,
          TError,
          Awaited<ReturnType<typeof getSeriesForPost>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSeriesForPost<
  TData = Awaited<ReturnType<typeof getSeriesForPost>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSeriesForPost>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSeriesForPost>>,
          TError,
          Awaited<ReturnType<typeof getSeriesForPost>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetSeriesForPost<
  TData = Awaited<ReturnType<typeof getSeriesForPost>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSeriesForPost>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Series For Post
 */

export function useGetSeriesForPost<
  TData = Awaited<ReturnType<typeof getSeriesForPost>>,
  TError = ErrorType<unknown>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSeriesForPost>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetSeriesForPostQueryOptions(slug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getProjectPostSeriesResponse200 = {
  data: GetPostSeriesListResponse;
  status: 200;
};

export type getProjectPostSeriesResponseSuccess =
  getProjectPostSeriesResponse200 & {
    headers: Headers;
  };
export type getProjectPostSeriesResponse = getProjectPostSeriesResponseSuccess;

export const getGetProjectPostSeriesUrl = (handle: string) => {
  return `/projects/${handle}/series`;
};

/**
 * 로그인 사용자가 해당 프로젝트에서 만든 본인 소유 시리즈 목록을 조회합니다.
 * @summary Get Project Post Series
 */
export const getProjectPostSeries = async (
  handle: string,
  options?: RequestInit,
): Promise<getProjectPostSeriesResponse> => {
  return api<getProjectPostSeriesResponse>(getGetProjectPostSeriesUrl(handle), {
    ...options,
    method: 'GET',
  });
};

export const getGetProjectPostSeriesQueryKey = (handle: string) => {
  return [`/projects/${handle}/series`] as const;
};

export const getGetProjectPostSeriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjectPostSeries>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectPostSeries>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProjectPostSeriesQueryKey(handle);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProjectPostSeries>>
  > = ({ signal }) =>
    getProjectPostSeries(handle, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: handle !== null && handle !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjectPostSeries>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectPostSeriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjectPostSeries>>
>;
export type GetProjectPostSeriesQueryError = ErrorType<unknown>;

export function useGetProjectPostSeries<
  TData = Awaited<ReturnType<typeof getProjectPostSeries>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectPostSeries>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectPostSeries>>,
          TError,
          Awaited<ReturnType<typeof getProjectPostSeries>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectPostSeries<
  TData = Awaited<ReturnType<typeof getProjectPostSeries>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectPostSeries>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectPostSeries>>,
          TError,
          Awaited<ReturnType<typeof getProjectPostSeries>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectPostSeries<
  TData = Awaited<ReturnType<typeof getProjectPostSeries>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectPostSeries>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Project Post Series
 */

export function useGetProjectPostSeries<
  TData = Awaited<ReturnType<typeof getProjectPostSeries>>,
  TError = ErrorType<unknown>,
>(
  handle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectPostSeries>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProjectPostSeriesQueryOptions(handle, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type createProjectPostSeriesResponse201 = {
  data: CreatePostSeriesResponse;
  status: 201;
};

export type createProjectPostSeriesResponseSuccess =
  createProjectPostSeriesResponse201 & {
    headers: Headers;
  };
export type createProjectPostSeriesResponse =
  createProjectPostSeriesResponseSuccess;

export const getCreateProjectPostSeriesUrl = (handle: string) => {
  return `/projects/${handle}/series`;
};

/**
 * 프로젝트에 시리즈를 생성합니다.
 * @summary Create Project Post Series
 */
export const createProjectPostSeries = async (
  handle: string,
  createPostSeriesRequest?: CreatePostSeriesRequest,
  options?: RequestInit,
): Promise<createProjectPostSeriesResponse> => {
  return api<createProjectPostSeriesResponse>(
    getCreateProjectPostSeriesUrl(handle),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(createPostSeriesRequest),
    },
  );
};

export const getCreateProjectPostSeriesMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createProjectPostSeries>>,
    TError,
    { handle: string; data?: CreatePostSeriesRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createProjectPostSeries>>,
  TError,
  { handle: string; data?: CreatePostSeriesRequest },
  TContext
> => {
  const mutationKey = ['createProjectPostSeries'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createProjectPostSeries>>,
    { handle: string; data?: CreatePostSeriesRequest }
  > = (props) => {
    const { handle, data } = props ?? {};

    return createProjectPostSeries(handle, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateProjectPostSeriesMutationResult = NonNullable<
  Awaited<ReturnType<typeof createProjectPostSeries>>
>;
export type CreateProjectPostSeriesMutationBody =
  | CreatePostSeriesRequest
  | undefined;
export type CreateProjectPostSeriesMutationError = ErrorType<unknown>;

/**
 * @summary Create Project Post Series
 */
export const useCreateProjectPostSeries = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createProjectPostSeries>>,
      TError,
      { handle: string; data?: CreatePostSeriesRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createProjectPostSeries>>,
  TError,
  { handle: string; data?: CreatePostSeriesRequest },
  TContext
> => {
  return useMutation(
    getCreateProjectPostSeriesMutationOptions(options),
    queryClient,
  );
};
export type createPostSeriesResponse201 = {
  data: CreatePostSeriesResponse;
  status: 201;
};

export type createPostSeriesResponseSuccess = createPostSeriesResponse201 & {
  headers: Headers;
};
export type createPostSeriesResponse = createPostSeriesResponseSuccess;

export const getCreatePostSeriesUrl = () => {
  return `/series`;
};

/**
 * 개인 시리즈를 생성합니다.
 * @summary Create Post Series
 */
export const createPostSeries = async (
  createPostSeriesRequest?: CreatePostSeriesRequest,
  options?: RequestInit,
): Promise<createPostSeriesResponse> => {
  return api<createPostSeriesResponse>(getCreatePostSeriesUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPostSeriesRequest),
  });
};

export const getCreatePostSeriesMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPostSeries>>,
    TError,
    { data?: CreatePostSeriesRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPostSeries>>,
  TError,
  { data?: CreatePostSeriesRequest },
  TContext
> => {
  const mutationKey = ['createPostSeries'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPostSeries>>,
    { data?: CreatePostSeriesRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createPostSeries(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePostSeriesMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPostSeries>>
>;
export type CreatePostSeriesMutationBody = CreatePostSeriesRequest | undefined;
export type CreatePostSeriesMutationError = ErrorType<unknown>;

/**
 * @summary Create Post Series
 */
export const useCreatePostSeries = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPostSeries>>,
      TError,
      { data?: CreatePostSeriesRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPostSeries>>,
  TError,
  { data?: CreatePostSeriesRequest },
  TContext
> => {
  return useMutation(getCreatePostSeriesMutationOptions(options), queryClient);
};
export type deletePostSeriesResponse204 = {
  data: void;
  status: 204;
};

export type deletePostSeriesResponseSuccess = deletePostSeriesResponse204 & {
  headers: Headers;
};
export type deletePostSeriesResponse = deletePostSeriesResponseSuccess;

export const getDeletePostSeriesUrl = (externalId: string) => {
  return `/series/${externalId}`;
};

/**
 * 시리즈를 삭제합니다.
 * @summary Delete Post Series
 */
export const deletePostSeries = async (
  externalId: string,
  options?: RequestInit,
): Promise<deletePostSeriesResponse> => {
  return api<deletePostSeriesResponse>(getDeletePostSeriesUrl(externalId), {
    ...options,
    method: 'DELETE',
  });
};

export const getDeletePostSeriesMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePostSeries>>,
    TError,
    { externalId: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePostSeries>>,
  TError,
  { externalId: string },
  TContext
> => {
  const mutationKey = ['deletePostSeries'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePostSeries>>,
    { externalId: string }
  > = (props) => {
    const { externalId } = props ?? {};

    return deletePostSeries(externalId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePostSeriesMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePostSeries>>
>;

export type DeletePostSeriesMutationError = ErrorType<unknown>;

/**
 * @summary Delete Post Series
 */
export const useDeletePostSeries = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePostSeries>>,
      TError,
      { externalId: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePostSeries>>,
  TError,
  { externalId: string },
  TContext
> => {
  return useMutation(getDeletePostSeriesMutationOptions(options), queryClient);
};
export type updatePostSeriesResponse204 = {
  data: void;
  status: 204;
};

export type updatePostSeriesResponseSuccess = updatePostSeriesResponse204 & {
  headers: Headers;
};
export type updatePostSeriesResponse = updatePostSeriesResponseSuccess;

export const getUpdatePostSeriesUrl = (externalId: string) => {
  return `/series/${externalId}`;
};

/**
 * 시리즈 정보를 수정합니다.
 * @summary Update Post Series
 */
export const updatePostSeries = async (
  externalId: string,
  updatePostSeriesRequest?: UpdatePostSeriesRequest,
  options?: RequestInit,
): Promise<updatePostSeriesResponse> => {
  return api<updatePostSeriesResponse>(getUpdatePostSeriesUrl(externalId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePostSeriesRequest),
  });
};

export const getUpdatePostSeriesMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePostSeries>>,
    TError,
    { externalId: string; data?: UpdatePostSeriesRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePostSeries>>,
  TError,
  { externalId: string; data?: UpdatePostSeriesRequest },
  TContext
> => {
  const mutationKey = ['updatePostSeries'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePostSeries>>,
    { externalId: string; data?: UpdatePostSeriesRequest }
  > = (props) => {
    const { externalId, data } = props ?? {};

    return updatePostSeries(externalId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdatePostSeriesMutationResult = NonNullable<
  Awaited<ReturnType<typeof updatePostSeries>>
>;
export type UpdatePostSeriesMutationBody = UpdatePostSeriesRequest | undefined;
export type UpdatePostSeriesMutationError = ErrorType<unknown>;

/**
 * @summary Update Post Series
 */
export const useUpdatePostSeries = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePostSeries>>,
      TError,
      { externalId: string; data?: UpdatePostSeriesRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updatePostSeries>>,
  TError,
  { externalId: string; data?: UpdatePostSeriesRequest },
  TContext
> => {
  return useMutation(getUpdatePostSeriesMutationOptions(options), queryClient);
};
export type addPostToPostSeriesResponse204 = {
  data: void;
  status: 204;
};

export type addPostToPostSeriesResponseSuccess =
  addPostToPostSeriesResponse204 & {
    headers: Headers;
  };
export type addPostToPostSeriesResponse = addPostToPostSeriesResponseSuccess;

export const getAddPostToPostSeriesUrl = (externalId: string) => {
  return `/series/${externalId}/posts`;
};

/**
 * 시리즈에 게시글을 추가합니다.
 * @summary Add Post To Series
 */
export const addPostToPostSeries = async (
  externalId: string,
  addPostToPostSeriesRequest?: AddPostToPostSeriesRequest,
  options?: RequestInit,
): Promise<addPostToPostSeriesResponse> => {
  return api<addPostToPostSeriesResponse>(
    getAddPostToPostSeriesUrl(externalId),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(addPostToPostSeriesRequest),
    },
  );
};

export const getAddPostToPostSeriesMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addPostToPostSeries>>,
    TError,
    { externalId: string; data?: AddPostToPostSeriesRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addPostToPostSeries>>,
  TError,
  { externalId: string; data?: AddPostToPostSeriesRequest },
  TContext
> => {
  const mutationKey = ['addPostToPostSeries'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addPostToPostSeries>>,
    { externalId: string; data?: AddPostToPostSeriesRequest }
  > = (props) => {
    const { externalId, data } = props ?? {};

    return addPostToPostSeries(externalId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddPostToPostSeriesMutationResult = NonNullable<
  Awaited<ReturnType<typeof addPostToPostSeries>>
>;
export type AddPostToPostSeriesMutationBody =
  | AddPostToPostSeriesRequest
  | undefined;
export type AddPostToPostSeriesMutationError = ErrorType<unknown>;

/**
 * @summary Add Post To Series
 */
export const useAddPostToPostSeries = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addPostToPostSeries>>,
      TError,
      { externalId: string; data?: AddPostToPostSeriesRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addPostToPostSeries>>,
  TError,
  { externalId: string; data?: AddPostToPostSeriesRequest },
  TContext
> => {
  return useMutation(
    getAddPostToPostSeriesMutationOptions(options),
    queryClient,
  );
};
export type removePostFromPostSeriesResponse204 = {
  data: void;
  status: 204;
};

export type removePostFromPostSeriesResponseSuccess =
  removePostFromPostSeriesResponse204 & {
    headers: Headers;
  };
export type removePostFromPostSeriesResponse =
  removePostFromPostSeriesResponseSuccess;

export const getRemovePostFromPostSeriesUrl = (
  externalId: string,
  seriesPostId: string,
) => {
  return `/series/${externalId}/posts/${seriesPostId}`;
};

/**
 * 시리즈에서 게시글을 제거합니다.
 * @summary Remove Post From Series
 */
export const removePostFromPostSeries = async (
  externalId: string,
  seriesPostId: string,
  options?: RequestInit,
): Promise<removePostFromPostSeriesResponse> => {
  return api<removePostFromPostSeriesResponse>(
    getRemovePostFromPostSeriesUrl(externalId, seriesPostId),
    {
      ...options,
      method: 'DELETE',
    },
  );
};

export const getRemovePostFromPostSeriesMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removePostFromPostSeries>>,
    TError,
    { externalId: string; seriesPostId: string },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removePostFromPostSeries>>,
  TError,
  { externalId: string; seriesPostId: string },
  TContext
> => {
  const mutationKey = ['removePostFromPostSeries'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removePostFromPostSeries>>,
    { externalId: string; seriesPostId: string }
  > = (props) => {
    const { externalId, seriesPostId } = props ?? {};

    return removePostFromPostSeries(externalId, seriesPostId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemovePostFromPostSeriesMutationResult = NonNullable<
  Awaited<ReturnType<typeof removePostFromPostSeries>>
>;

export type RemovePostFromPostSeriesMutationError = ErrorType<unknown>;

/**
 * @summary Remove Post From Series
 */
export const useRemovePostFromPostSeries = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removePostFromPostSeries>>,
      TError,
      { externalId: string; seriesPostId: string },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof removePostFromPostSeries>>,
  TError,
  { externalId: string; seriesPostId: string },
  TContext
> => {
  return useMutation(
    getRemovePostFromPostSeriesMutationOptions(options),
    queryClient,
  );
};
export type reorderPostSeriesPostResponse204 = {
  data: void;
  status: 204;
};

export type reorderPostSeriesPostResponseSuccess =
  reorderPostSeriesPostResponse204 & {
    headers: Headers;
  };
export type reorderPostSeriesPostResponse =
  reorderPostSeriesPostResponseSuccess;

export const getReorderPostSeriesPostUrl = (
  externalId: string,
  seriesPostId: string,
) => {
  return `/series/${externalId}/posts/${seriesPostId}`;
};

/**
 * 시리즈 내 게시글의 순서를 변경합니다.
 * @summary Reorder Post In Series
 */
export const reorderPostSeriesPost = async (
  externalId: string,
  seriesPostId: string,
  reorderPostSeriesPostRequest?: ReorderPostSeriesPostRequest,
  options?: RequestInit,
): Promise<reorderPostSeriesPostResponse> => {
  return api<reorderPostSeriesPostResponse>(
    getReorderPostSeriesPostUrl(externalId, seriesPostId),
    {
      ...options,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(reorderPostSeriesPostRequest),
    },
  );
};

export const getReorderPostSeriesPostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reorderPostSeriesPost>>,
    TError,
    {
      externalId: string;
      seriesPostId: string;
      data?: ReorderPostSeriesPostRequest;
    },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof reorderPostSeriesPost>>,
  TError,
  {
    externalId: string;
    seriesPostId: string;
    data?: ReorderPostSeriesPostRequest;
  },
  TContext
> => {
  const mutationKey = ['reorderPostSeriesPost'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reorderPostSeriesPost>>,
    {
      externalId: string;
      seriesPostId: string;
      data?: ReorderPostSeriesPostRequest;
    }
  > = (props) => {
    const { externalId, seriesPostId, data } = props ?? {};

    return reorderPostSeriesPost(
      externalId,
      seriesPostId,
      data,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type ReorderPostSeriesPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof reorderPostSeriesPost>>
>;
export type ReorderPostSeriesPostMutationBody =
  | ReorderPostSeriesPostRequest
  | undefined;
export type ReorderPostSeriesPostMutationError = ErrorType<unknown>;

/**
 * @summary Reorder Post In Series
 */
export const useReorderPostSeriesPost = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reorderPostSeriesPost>>,
      TError,
      {
        externalId: string;
        seriesPostId: string;
        data?: ReorderPostSeriesPostRequest;
      },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof reorderPostSeriesPost>>,
  TError,
  {
    externalId: string;
    seriesPostId: string;
    data?: ReorderPostSeriesPostRequest;
  },
  TContext
> => {
  return useMutation(
    getReorderPostSeriesPostMutationOptions(options),
    queryClient,
  );
};
